#!/usr/bin/env python3
"""Enumeration-tree certificate generator (untrusted).

Exact-dedup BFS over `next_tame p` from `Seed p` using the Python reference
implementation (enumerate.py): a child that is LITERALLY equal (same record)
to an already-visited node is not re-expanded.  This preserves the closure
property exactly — expansion results depend only on the record value, so no
isomorphism machinery is needed for closure (unlike the AFP trie worklist,
which dedups only the collected final set and expands the full tree).

Emitted Lean data (namespace Kepler.Graphs):

  <Name>Nodes    : List Graph        -- every visited node; node 0 = Seed p
  <Name>Children : List (List Nat)   -- per node, indices of its next_tame children
  <Name>Finals   : List (Nat × Nat)  -- (node index, archive index) per final node

The Lean checker re-verifies EVERYTHING from this data:
  - per node i, one kernel `decide`:
    `next_tame p nodes[i]! = children[i]!.map nodes.get!`
  - children indices in range; every final node appears exactly once in Finals
  - per finals entry (i, j): `pre_iso_test` (both sides) and
    `iso_test (fgraph nodes[i]!) archive[j]!` by kernel `decide`

Usage: python3 certgen.py <p> <archive.ml> <out.lean> [Name]
"""
import sys
import pathlib
from collections import deque

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import enumerate as E
import crosscheck as C

SEED_NAME = {0: "Tri", 1: "Quad", 2: "Pent", 3: "Hex"}


def face_lean(f):
    vs = ", ".join(map(str, f[0]))
    return f"⟨[{vs}], {'true' if f[1] else 'false'}⟩"


def graph_lean(g):
    fs = ", ".join(face_lean(f) for f in E.faces(g))
    fla = ", ".join("[" + ", ".join(face_lean(f) for f in fl) + "]"
                     for fl in E.faceListAt(g))
    hs = ", ".join(map(str, E.heights(g)))
    return f"⟨[{fs}], {E.countVertices(g)}, [{fla}], [{hs}]⟩"


def build_arrays(p):
    """Exact-dedup BFS. Returns (nodes, children, finals)."""
    nodes = [E.Seed(p)]
    index = {repr(nodes[0]): 0}
    children = []
    finals = []
    queue = deque([0])
    while queue:
        i = queue.popleft()
        g = nodes[i]
        cs = E.next_tame(p, g)
        idx = []
        for c in cs:
            k = repr(c)
            j = index.get(k)
            if j is None:
                j = len(nodes)
                index[k] = j
                nodes.append(c)
                queue.append(j)
            idx.append(j)
        children.append(idx)
        if E.finalGraph(g):
            finals.append(i)
    return nodes, children, finals


def emit(p, ml, out, name):
    nodes, children, finals = build_arrays(p)
    assert len(children) == len(nodes) - 0 or True
    arch = C.parse_ml_archive(ml)
    arch_codes = {}
    for j, fg in enumerate(arch):
        arch_codes.setdefault(C.canonical(fg), j)
    table = []
    for i in finals:
        code = C.canonical(E.fgraph(nodes[i]))
        if code not in arch_codes:
            raise SystemExit(f"final node {i} has no archive match!")
        table.append((i, arch_codes[code]))

    with open(out, "w") as f:
        f.write(f"""/-
Enumeration certificate for seed p={p} ({name}), UNTRUSTED data.

Generated by `pipeline/graphs/certgen.py`; verified node-by-node by the Lean
kernel checker.  {len(nodes)} nodes (exact-dedup BFS), {len(finals)} final
graphs, archive matches into `{name}Data`.
-/
import Kepler.Graphs.TameEnum
import Kepler.Graphs.ArchiveData.{name}

namespace Kepler.Graphs

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Visited nodes; node 0 is `Seed {p}`.  {len(nodes)} nodes. -/
def {name}Nodes : List Graph := [
""")
        f.write(",\n".join("  " + graph_lean(g) for g in nodes))
        f.write("\n]\n\n")
        f.write(f"""set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Per-node indices of the `next_tame {p}` children into `{name}Nodes`. -/
def {name}Children : List (List Nat) := [
""")
        f.write(",\n".join("  [" + ", ".join(map(str, c)) + "]" for c in children))
        f.write("\n]\n\n")
        f.write(f"""/-- (node index, archive index into `{name}Data`) per final node.
{len(table)} entries. -/
def {name}Finals : List (Nat × Nat) := [
""")
        f.write(",\n".join(f"  ({i}, {j})" for i, j in table))
        f.write("\n]\n\nend Kepler.Graphs\n")
    print(f"{name}: {len(nodes)} nodes, {len(finals)} finals -> {out}",
          flush=True)


def build_top(p, depth):
    """BFS levels. Returns (S, S_children, F, S_finals):
    S = nodes at depth < depth (with children tagged (is_F, index)),
    F = nodes at level `depth`, S_finals = indices of final nodes in S."""
    S = [E.Seed(p)]
    index = {repr(S[0]): 0}
    queue = deque([0])
    depths = [0]
    F = []
    findex = {}
    children = []
    finals = []
    while queue:
        i = queue.popleft()
        g = S[i]
        if E.finalGraph(g):
            children.append([])
            finals.append(i)
            continue
        if depths[i] >= depth:
            raise SystemExit("internal: node beyond frontier expanded")
        idx = []
        for c in E.next_tame(p, g):
            k = repr(c)
            if depths[i] + 1 >= depth:
                j = findex.get(k)
                if j is None:
                    j = len(F)
                    findex[k] = j
                    F.append(c)
                idx.append((True, j))
            else:
                j = index.get(k)
                if j is None:
                    j = len(S)
                    index[k] = j
                    S.append(c)
                    depths.append(depths[i] + 1)
                    queue.append(j)
                idx.append((False, j))
        children.append(idx)
    return S, children, F, finals


def emit_top(p, depth, ml, out, name):
    """Emit the shard certificate: S (top nodes), per-node children tagged
    (isF, index), F (frontier = shard roots), finals table for S."""
    S, children, F, s_finals = build_top(p, depth)
    arch = C.parse_ml_archive(ml)
    arch_codes = {}
    for j, fg in enumerate(arch):
        arch_codes.setdefault(C.canonical(fg), j)
    table = []
    for i in s_finals:
        code = C.canonical(E.fgraph(S[i]))
        if code not in arch_codes:
            raise SystemExit(f"top final node {i} has no archive match!")
        table.append((i, arch_codes[code]))
    with open(out, "w") as f:
        f.write(f"""/-
Shard certificate for seed p={p} ({name}), UNTRUSTED data.
Generated by `pipeline/graphs/certgen.py` (emit_top, depth={depth}).
|top| = {len(S)} nodes, |frontier| = {len(F)} shard roots,
{len(table)} final nodes in the top.
-/
import Kepler.Graphs.TameEnum
import Kepler.Graphs.ArchiveData.{name}

namespace Kepler.Graphs

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Top nodes (BFS depth < {depth}); node 0 is `Seed {p}`. -/
def {name}Top : List Graph := [
""")
        f.write(",\n".join("  " + graph_lean(g) for g in S))
        f.write("\n]\n\n")
        f.write("set_option maxRecDepth 1000000 in\nset_option maxHeartbeats 0 in\n")
        f.write(f"""/-- Per top node: children as (isFrontier, index) into
`{name}Frontier` resp. `{name}Top`. -/
def {name}TopChildren : List (List (Bool × Nat)) := [
""")
        f.write(",\n".join("  [" + ", ".join(f"({'true' if b else 'false'}, {j})"
                                               for b, j in c) + "]"
                           for c in children))
        f.write("\n]\n\n")
        f.write("set_option maxRecDepth 1000000 in\nset_option maxHeartbeats 0 in\n")
        f.write(f"/-- Frontier nodes (BFS depth = {depth}); the shard roots. -/\ndef {name}Frontier : List Graph := [\n")
        f.write(",\n".join("  " + graph_lean(g) for g in F))
        f.write("\n]\n\n")
        f.write(f"""/-- (node index into `{name}Top`, archive index into `{name}Data`)
for each final node in the top. {len(table)} entries. -/
def {name}TopFinals : List (Nat × Nat) := [
""")
        f.write(",\n".join(f"  ({i}, {j})" for i, j in table))
        f.write("\n]\n\nend Kepler.Graphs\n")
    print(f"{name} top: |S|={len(S)} |F|={len(F)} finals={len(table)} -> {out}",
          flush=True)


if __name__ == "__main__":
    if sys.argv[1] == "top":
        # certgen.py top <p> <depth> <archive.ml> <out.lean> [Name]
        p = int(sys.argv[2])
        depth = int(sys.argv[3])
        ml = sys.argv[4]
        out = sys.argv[5]
        name = sys.argv[6] if len(sys.argv) > 6 else SEED_NAME[p]
        emit_top(p, depth, ml, out, name)
    else:
        p = int(sys.argv[1])
        ml = sys.argv[2]
        out = sys.argv[3]
        name = sys.argv[4] if len(sys.argv) > 4 else SEED_NAME[p]
        emit(p, ml, out, name)
