#!/usr/bin/env python3
"""Convert AFP Flyspeck-Tame Archive .ML files to Lean data modules.

Input : reference/afp-flyspeck-tame/Archives/{Tri,Quad,Pent,Hex}.ML
        (each is `val Name' = [ <fgraph>, ... ]`, fgraph = list of faces,
        face = list of nat vertices)
Output: lean/Kepler/Graphs/ArchiveData/<Name>.lean defining `def <name>Data`.

The data is UNTRUSTED input to the certificate pipeline; correctness comes
from the kernel-replayed checkers, not from this conversion.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "reference" / "afp-flyspeck-tame" / "Archives"
DST = ROOT / "lean" / "Kepler" / "Graphs" / "ArchiveData"

HEADER = """/-
Archive data: the Flyspeck-Tame archive of tame plane graphs.

Source: `reference/afp-flyspeck-tame/Archives/{name}.ML`
(afp-Flyspeck-Tame-current, locked in `reference/LOCK.md`;
byte-identical to `reference/flyspeck/formal_graph/archive/{name}.ML`).

Machine-generated by `pipeline/graphs/ml_to_lean.py`. Each entry is an
fgraph: a list of faces, each face a list of vertex indices (`Nat`),
exactly as in the AFP `Arch.thy` constants (via `nat_of_integer`).
-/
namespace Kepler.Graphs

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- AFP `Arch.thy: {name}` ({count} fgraphs). -/
def {name}Data : List (List (List Nat)) := [
"""


def convert(name: str) -> None:
    text = (SRC / f"{name}.ML").read_text()
    # strip the `val Name' =` prefix and trailing whitespace/semicolon
    body = re.sub(r"^\s*val\s+\w+'\s*=\s*", "", text).strip().rstrip(";")
    graphs = eval(body)  # trusted local reference data; pure list of ints
    assert isinstance(graphs, list)
    out = [HEADER.format(name=name, count=len(graphs))]
    for g in graphs:
        faces = ", ".join("[" + ", ".join(map(str, f)) + "]" for f in g)
        out.append(f"  [{faces}]\n" if False else f"  [{faces}],\n")
    # remove trailing comma of last entry, close the list
    out[-1] = out[-1].rstrip(",\n") + "\n"
    out.append("]\n\nend Kepler.Graphs\n")
    DST.mkdir(parents=True, exist_ok=True)
    (DST / f"{name}.lean").write_text("".join(out))
    print(f"{name}: {len(graphs)} graphs -> {DST / f'{name}.lean'}")


if __name__ == "__main__":
    for name in (sys.argv[1:] or ["Tri", "Quad", "Pent", "Hex"]):
        convert(name)
