/-
AUTO-GENERATED certificate (column-major mode) — do not edit

Generated by `pipeline/lp/socert.py --col-major` from `pilot_204880136538_flat.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 915 vars, 3882 rows.
Constraint matrix stored BY COLUMN (`LPCM.cs`); the dual check is O(nnz).
Dual certificate: y = Y/D with D = certD, claimed bound γ = certG/certD.
The dual vector Y is a plain `List Int`; the tree `ITree.ofList certY 12`
(2^12 = 4096 leaves ≥ 3882 rows) is built transiently inside the decide.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.PilotCM204880136538.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kepler.LP.PilotCM204880136538

/-- The whole column loop `AᵀY ≥ D·c` over all 915 columns: with the
column-major layout this is a single O(nnz) kernel `decide`. -/
theorem cols_check : checkDualCMTCols lp d (ITree.ofList certY d) certD = true := by
  decide

/-- Reassembly: flat base checks + column loop give the full dual certificate. -/
theorem dual_check : checkDualCMTF lp d (ITree.ofList certY d) certY certD certG = true :=
  checkDualCMTF_split base_check cols_check

/-- End-to-end: every rational-feasible point of `lp` has objective
≤ `certG / certD`.  Feasibility is stated over the column-major data
(`cmRowEval`). -/
theorem bound (x : List Rat) (hxlen : x.length = lp.cs.length)
    (hx0 : ∀ j < lp.cs.length, 0 ≤ x.getD j 0)
    (hxrows : ∀ i < lp.b.length, cmRowEval lp i x ≤ (lp.b.getD i 0 : Rat)) :
    cmObj lp x ≤ ((certG : Int) : Rat) / ((certD : ℕ) : Rat) :=
  checkDualCMTF_sound lp d certY certD certG dual_check x hxlen hx0 hxrows

/-- The Flyspeck terminal condition `γ < 12`, as an integer inequality
(`G < 12·D` ⟺ `G/D < 12` since `D > 0`). -/
theorem gamma_lt : certG < 12 * (certD : Int) := by
  decide

/-- The terminal condition transported to the objective: every
rational-feasible point has objective `< 12`. -/
theorem bound_lt (x : List Rat) (hxlen : x.length = lp.cs.length)
    (hx0 : ∀ j < lp.cs.length, 0 ≤ x.getD j 0)
    (hxrows : ∀ i < lp.b.length, cmRowEval lp i x ≤ (lp.b.getD i 0 : Rat)) :
    cmObj lp x < 12 := by
  refine lt_of_le_of_lt (bound x hxlen hx0 hxrows) ?_
  have hD : (0 : Rat) < ((certD : ℕ) : Rat) := Nat.cast_pos.mpr (by decide)
  rw [div_lt_iff₀ hD]
  calc ((certG : Int) : Rat) < ((12 * (certD : Int) : Int) : Rat) :=
        Int.cast_lt.mpr gamma_lt
    _ = 12 * ((certD : ℕ) : Rat) := by push_cast; ring

end Kepler.LP.PilotCM204880136538
