/-
AUTO-GENERATED certificate — do not edit

Generated by `pipeline/lp/socert.py` from `hello.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 2 vars, 2 rows.
Dual certificate: y = Y/D with D = 3, claimed bound γ = G/D = 3.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.Cert

namespace Kepler.LP.CertHello

/-- The LP, sparse integer data (`hello.lp`). -/
def lp : LPI where
  numVars := 2
  c := [(0, 1), (1, 1)]
  A := [
    ⟨[(0, 2), (1, 1)], 4⟩,
    ⟨[(0, 1), (1, 2)], 5⟩]

/-- Kernel re-check of the integerized dual certificate. -/
theorem dual_check : checkDual lp [1, 1] 3 9 = true := by decide

/-- End-to-end: every rational-feasible point of `lp` has objective ≤ 3. -/
theorem bound (x : List Rat) (hxlen : x.length = lp.numVars)
    (hx0 : ∀ j < lp.numVars, 0 ≤ x.getD j 0)
    (hxA : ∀ r ∈ lp.A, r.evalRat x ≤ (r.rhs : Rat)) :
    lp.c.dotRat x ≤ 3 := by
  have h := checkDual_sound lp [1, 1] 3 9 dual_check x hxlen hx0 hxA
  rwa [show ((9 : Int) : Rat) / ((3 : ℕ) : Rat) = 3 by norm_num] at h

/-- The SoPlex primal solution is integral; the kernel checks feasibility. -/
theorem primal_check : checkPrimal lp [1, 2] = true := by decide

end Kepler.LP.CertHello
