/-
AUTO-GENERATED certificate — do not edit

Generated by `pipeline/lp/socert.py` from `hello-frac.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 2 vars, 2 rows.
Dual certificate: y = Y/D with D = 3, claimed bound γ = G/D = 10/3.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.Cert

namespace Kepler.LP.CertHelloFrac

/-- The LP, sparse integer data (`hello-frac.lp`). -/
def lp : LPI where
  numVars := 2
  c := [(0, 1), (1, 1)]
  A := [
    ⟨[(0, 2), (1, 1)], 5⟩,
    ⟨[(0, 1), (1, 2)], 5⟩]

/-- Kernel re-check of the integerized dual certificate. -/
theorem dual_check : checkDual lp [1, 1] 3 10 = true := by decide

/-- End-to-end: every rational-feasible point of `lp` has objective ≤ 10/3. -/
theorem bound (x : List Rat) (hxlen : x.length = lp.numVars)
    (hx0 : ∀ j < lp.numVars, 0 ≤ x.getD j 0)
    (hxA : ∀ r ∈ lp.A, r.evalRat x ≤ (r.rhs : Rat)) :
    lp.c.dotRat x ≤ (10/3 : Rat) := by
  have h := checkDual_sound lp [1, 1] 3 10 dual_check x hxlen hx0 hxA
  rwa [show ((10 : Int) : Rat) / ((3 : ℕ) : Rat) = (10/3 : Rat) by norm_num] at h

-- The SoPlex primal solution is fractional (x = 5/3, 5/3);
-- the Int-valued `checkPrimal` does not apply, the dual certificate suffices.

end Kepler.LP.CertHelloFrac
