/-
AUTO-GENERATED certificate — do not edit

Generated by `pipeline/lp/socert.py` from `rand-12x20.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 20 vars, 12 rows.
Dual certificate: y = Y/D with D = 111, claimed bound γ = G/D = 19969/111.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.Cert

namespace Kepler.LP.CertRand12x20

/-- The LP, sparse integer data (`rand-12x20.lp`). -/
def lp : LPI where
  numVars := 20
  c := [(0, 1), (1, 4), (2, 9), (3, 6), (4, 3), (5, 9), (6, 1), (7, 9), (8, 5), (9, 2), (10, 5), (11, 9), (12, 6), (13, 3), (14, 6), (15, 4), (16, 9), (17, 9), (18, 9), (19, 6)]
  A := [
    ⟨[(0, 1), (2, 2), (3, 4), (6, 5), (7, 3), (9, 1), (10, 3), (12, 3), (16, 2), (17, 2)], 19⟩,
    ⟨[(1, 3), (2, 2), (4, 5), (5, 3), (8, 4), (9, 4), (10, 3), (12, 3), (13, 3), (14, 2), (18, 3), (19, 5)], 41⟩,
    ⟨[(1, 1), (2, 2), (4, 3), (6, 3), (7, 1), (8, 3), (9, 5), (10, 4), (13, 3), (14, 3), (15, 4), (17, 1), (19, 3)], 28⟩,
    ⟨[(0, 4), (2, 3), (4, 3), (6, 2), (7, 4), (8, 3), (9, 2), (10, 5), (11, 1), (12, 2), (13, 3), (14, 2), (15, 1), (16, 1), (18, 5)], 32⟩,
    ⟨[(0, 4), (1, 5), (4, 3), (5, 1), (6, 3), (7, 2), (8, 1), (9, 4), (10, 2), (11, 1), (12, 3), (15, 3), (16, 2), (18, 5), (19, 1)], 45⟩,
    ⟨[(1, 2), (2, 2), (4, 4), (6, 5), (7, 3), (8, 3), (9, 5), (10, 5), (11, 1), (12, 1), (13, 4), (14, 1), (15, 3), (16, 2), (17, 3), (18, 5), (19, 2)], 46⟩,
    ⟨[(1, 5), (3, 1), (4, 2), (5, 4), (6, 4), (9, 4), (10, 4), (11, 1), (12, 4), (13, 3), (14, 4), (15, 5), (16, 2), (17, 1), (18, 4), (19, 2)], 53⟩,
    ⟨[(0, 4), (1, 1), (3, 2), (4, 1), (6, 3), (8, 2), (11, 5), (12, 1), (14, 4), (16, 2), (17, 2), (18, 5), (19, 2)], 37⟩,
    ⟨[(2, 2), (3, 2), (4, 3), (5, 1), (7, 5), (8, 2), (9, 5), (10, 3), (11, 1), (12, 4), (13, 2), (14, 1), (15, 4), (16, 2)], 27⟩,
    ⟨[(3, 4), (6, 2), (7, 5), (8, 3), (10, 1), (11, 1), (14, 2), (15, 3), (16, 1), (17, 3), (18, 3), (19, 1)], 24⟩,
    ⟨[(1, 4), (2, 5), (3, 3), (4, 3), (5, 4), (6, 4), (7, 4), (9, 2), (10, 5), (11, 5), (12, 5), (13, 4), (14, 5), (15, 3), (16, 2), (17, 2), (18, 2), (19, 2)], 55⟩,
    ⟨[(1, 2), (2, 4), (3, 2), (8, 2), (11, 1), (12, 3), (16, 3), (18, 3)], 23⟩]

/-- Kernel re-check of the integerized dual certificate. -/
theorem dual_check : checkDual lp [111, 25, 0, 0, 0, 0, 0, 0, 0, 105, 231, 70] 111 19969 = true := by decide

/-- End-to-end: every rational-feasible point of `lp` has objective ≤ 19969/111. -/
theorem bound (x : List Rat) (hxlen : x.length = lp.numVars)
    (hx0 : ∀ j < lp.numVars, 0 ≤ x.getD j 0)
    (hxA : ∀ r ∈ lp.A, r.evalRat x ≤ (r.rhs : Rat)) :
    lp.c.dotRat x ≤ (19969/111 : Rat) := by
  have h := checkDual_sound lp [111, 25, 0, 0, 0, 0, 0, 0, 0, 105, 231, 70] 111 19969 dual_check x hxlen hx0 hxA
  rwa [show ((19969 : Int) : Rat) / ((111 : ℕ) : Rat) = (19969/111 : Rat) by norm_num] at h

-- The SoPlex primal solution is fractional (x = 208/111, 0, 0, 0, 0, 1051/111, 0, 0, 233/74, 0, 0, 0, 0, 0, 0, 0, 206/37, 665/222, 0, 0);
-- the Int-valued `checkPrimal` does not apply, the dual certificate suffices.

end Kepler.LP.CertRand12x20
