/-
AUTO-GENERATED certificate (sharded mode) — do not edit

Generated by `pipeline/lp/socert.py --shard-cols 4` from `rand-12x20.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 20 vars, 12 rows.
Dual certificate: y = Y/D with D = certD, claimed bound γ = certG/certD.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.RandShard12x20.Cols000
import Kepler.LP.RandShard12x20.Cols001
import Kepler.LP.RandShard12x20.Cols002
import Kepler.LP.RandShard12x20.Cols003
import Kepler.LP.RandShard12x20.Cols004

namespace Kepler.LP.RandShard12x20

/-- Shard chain: `cols_<i>` covers columns `[0, i·4)`. Term-mode links:
no kernel re-evaluation of the shards. -/
theorem cols_0 : checkDualColShards lp certY certD 20 4 0 = true := rfl

theorem cols_1 : checkDualColShards lp certY certD 20 4 (0 + 1) = true :=
  Bool.and_eq_true_iff.mpr ⟨cols_0, shard_0⟩

theorem cols_2 : checkDualColShards lp certY certD 20 4 (1 + 1) = true :=
  Bool.and_eq_true_iff.mpr ⟨cols_1, shard_1⟩

theorem cols_3 : checkDualColShards lp certY certD 20 4 (2 + 1) = true :=
  Bool.and_eq_true_iff.mpr ⟨cols_2, shard_2⟩

theorem cols_4 : checkDualColShards lp certY certD 20 4 (3 + 1) = true :=
  Bool.and_eq_true_iff.mpr ⟨cols_3, shard_3⟩

theorem cols_5 : checkDualColShards lp certY certD 20 4 (4 + 1) = true :=
  Bool.and_eq_true_iff.mpr ⟨cols_4, shard_4⟩

/-- Reassembly: the sharded checks give the full dual certificate. -/
theorem dual_check : checkDual lp certY certD certG = true :=
  checkDual_of_shards lp certY certD certG 4 5 (by decide)
    base_check cols_5

/-- End-to-end: every rational-feasible point of `lp` has objective
≤ `certG / certD`. -/
theorem bound (x : List Rat) (hxlen : x.length = lp.numVars)
    (hx0 : ∀ j < lp.numVars, 0 ≤ x.getD j 0)
    (hxA : ∀ r ∈ lp.A, r.evalRat x ≤ (r.rhs : Rat)) :
    lp.c.dotRat x ≤ ((certG : Int) : Rat) / ((certD : ℕ) : Rat) :=
  checkDual_sound lp certY certD certG dual_check x hxlen hx0 hxA

/-- The Flyspeck terminal condition `γ < 200`, as an integer inequality
(`G < 200·D` ⟺ `G/D < 200` since `D > 0`). -/
theorem gamma_lt : certG < 200 * (certD : Int) := by
  decide

/-- The terminal condition transported to the objective: every
rational-feasible point has objective `< 200`. -/
theorem bound_lt (x : List Rat) (hxlen : x.length = lp.numVars)
    (hx0 : ∀ j < lp.numVars, 0 ≤ x.getD j 0)
    (hxA : ∀ r ∈ lp.A, r.evalRat x ≤ (r.rhs : Rat)) :
    lp.c.dotRat x < 200 := by
  refine lt_of_le_of_lt (bound x hxlen hx0 hxA) ?_
  have hD : (0 : Rat) < ((certD : ℕ) : Rat) := Nat.cast_pos.mpr (by decide)
  rw [div_lt_iff₀ hD]
  calc ((certG : Int) : Rat) < ((200 * (certD : Int) : Int) : Rat) :=
        Int.cast_lt.mpr gamma_lt
    _ = 200 * ((certD : ℕ) : Rat) := by push_cast; ring

end Kepler.LP.RandShard12x20
