/-
AUTO-GENERATED certificate (sharded mode) — do not edit

Generated by `pipeline/lp/socert.py --shard-cols 4` from `rand-12x20.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 20 vars, 12 rows.
Dual certificate: y = Y/D with D = certD, claimed bound γ = certG/certD.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.RandShard12x20.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kepler.LP.RandShard12x20

/-- Column shard 2: `AᵀY ≥ D·c` restricted to columns [8, 12). -/
theorem shard_2 : checkDualCols lp certY certD 8 4 = true := by
  decide

end Kepler.LP.RandShard12x20
