/-
AUTO-GENERATED certificate (sharded mode) — do not edit

Generated by `pipeline/lp/socert.py --shard-cols 4` from `rand-12x20.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 20 vars, 12 rows.
Dual certificate: y = Y/D with D = certD, claimed bound γ = certG/certD.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.Cert

-- deep list literals and the kernel `decide` re-check need headroom
set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kepler.LP.RandShard12x20

/-- The LP, sparse integer data (`rand-12x20.lp`). -/
def lp : LPI where
  numVars := 20
  c := [(0, 1), (1, 4), (2, 9), (3, 6), (4, 3), (5, 9), (6, 1), (7, 9), (8, 5), (9, 2), (10, 5), (11, 9), (12, 6), (13, 3), (14, 6), (15, 4), (16, 9), (17, 9), (18, 9), (19, 6)]
  A := [
    ⟨[(0, 1), (2, 2), (3, 4), (6, 5), (7, 3), (9, 1), (10, 3), (12, 3), (16, 2), (17, 2)], 19⟩,
    ⟨[(1, 3), (2, 2), (4, 5), (5, 3), (8, 4), (9, 4), (10, 3), (12, 3), (13, 3), (14, 2), (18, 3), (19, 5)], 41⟩,
    ⟨[(1, 1), (2, 2), (4, 3), (6, 3), (7, 1), (8, 3), (9, 5), (10, 4), (13, 3), (14, 3), (15, 4), (17, 1), (19, 3)], 28⟩,
    ⟨[(0, 4), (2, 3), (4, 3), (6, 2), (7, 4), (8, 3), (9, 2), (10, 5), (11, 1), (12, 2), (13, 3), (14, 2), (15, 1), (16, 1), (18, 5)], 32⟩,
    ⟨[(0, 4), (1, 5), (4, 3), (5, 1), (6, 3), (7, 2), (8, 1), (9, 4), (10, 2), (11, 1), (12, 3), (15, 3), (16, 2), (18, 5), (19, 1)], 45⟩,
    ⟨[(1, 2), (2, 2), (4, 4), (6, 5), (7, 3), (8, 3), (9, 5), (10, 5), (11, 1), (12, 1), (13, 4), (14, 1), (15, 3), (16, 2), (17, 3), (18, 5), (19, 2)], 46⟩,
    ⟨[(1, 5), (3, 1), (4, 2), (5, 4), (6, 4), (9, 4), (10, 4), (11, 1), (12, 4), (13, 3), (14, 4), (15, 5), (16, 2), (17, 1), (18, 4), (19, 2)], 53⟩,
    ⟨[(0, 4), (1, 1), (3, 2), (4, 1), (6, 3), (8, 2), (11, 5), (12, 1), (14, 4), (16, 2), (17, 2), (18, 5), (19, 2)], 37⟩,
    ⟨[(2, 2), (3, 2), (4, 3), (5, 1), (7, 5), (8, 2), (9, 5), (10, 3), (11, 1), (12, 4), (13, 2), (14, 1), (15, 4), (16, 2)], 27⟩,
    ⟨[(3, 4), (6, 2), (7, 5), (8, 3), (10, 1), (11, 1), (14, 2), (15, 3), (16, 1), (17, 3), (18, 3), (19, 1)], 24⟩,
    ⟨[(1, 4), (2, 5), (3, 3), (4, 3), (5, 4), (6, 4), (7, 4), (9, 2), (10, 5), (11, 5), (12, 5), (13, 4), (14, 5), (15, 3), (16, 2), (17, 2), (18, 2), (19, 2)], 55⟩,
    ⟨[(1, 2), (2, 4), (3, 2), (8, 2), (11, 1), (12, 3), (16, 3), (18, 3)], 23⟩]

/-- The integerized dual solution `Y` (the rational dual is `Y/certD`). -/
def certY : List Int := [111, 25, 0, 0, 0, 0, 0, 0, 0, 105, 231, 70]

/-- The certificate denominator `D > 0`. -/
def certD : ℕ := 111

/-- The integerized bound numerator: `γ = certG / certD`. -/
def certG : Int := 19969

/-- Everything except the column loop: `D > 0`, sizes, well-formedness,
`Y ≥ 0`, and `bᵀY ≤ G`. -/
theorem base_check : checkDualBase lp certY certD certG = true := by
  decide

end Kepler.LP.RandShard12x20
