/-
  Phase 4, G4 certificate (auto-generated by pipeline/interval/emit_lean.py).
  case: 1965189142 34  (orig_op: <, vars: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'])
  cert: 1 leaf/leaves, prec 64 (bb_arb)
  Do not edit by hand.
-/
import Kepler.Interval.Cert

namespace Kepler.Interval.Cases

/-- The case expression (RPN prog mirrored as `IExpr`). -/
def C1965189142x34Expr : IExpr 6 :=
  (.sub (.const ⟨0, 0⟩) (.add (.sub (.div (.const ⟨591, 0⟩) (.const ⟨1000, 0⟩) (-64)) (.mul (.div (.const ⟨331, 0⟩) (.const ⟨10000, 0⟩) (-64)) (.const ⟨34, 0⟩))) (.mul (.div (.const ⟨253, 0⟩) (.const ⟨500, 0⟩) (-64)) (.div (.sub (.div (.const ⟨63, 0⟩) (.const ⟨50, 0⟩) (-64)) (.var 0)) (.sub (.div (.const ⟨63, 0⟩) (.const ⟨50, 0⟩) (-64)) (.const ⟨1, 0⟩)) (-64)))))

/-- The target box (dyadic q-expansion of the original decimal box). -/
def C1965189142x34Box : Fin 6 → DInterval :=
  ![⟨⟨1, 0⟩, ⟨1352914699, -30⟩⟩, ⟨⟨1, 0⟩, ⟨1, 0⟩⟩, ⟨⟨1, 0⟩, ⟨1, 0⟩⟩, ⟨⟨1, 0⟩, ⟨1, 0⟩⟩, ⟨⟨1, 0⟩, ⟨1, 0⟩⟩, ⟨⟨1, 0⟩, ⟨1, 0⟩⟩]

/-- Whole-box positivity certificate (kernel `decide`). -/
theorem C1965189142x34_cert : checkPos C1965189142x34Expr C1965189142x34Box = true := by
  decide

/-- The one-leaf certificate tree. -/
def C1965189142x34Tree : BBTree 6 C1965189142x34Expr :=
  .leaf C1965189142x34Box C1965189142x34_cert

/-- A single leaf trivially covers itself. -/
theorem C1965189142x34_covers : C1965189142x34Tree.covers :=
  trivial

/-- Box containment is reflexive here (tree root = target box). -/
theorem C1965189142x34_sub : boxSub C1965189142x34Box C1965189142x34Tree.box := by
  intro i
  fin_cases i <;> exact ⟨by decide, by decide⟩

/-- End-to-end: the case expression is strictly positive on the whole box. -/
theorem C1965189142x34_pos (ρ : Fin 6 → ℝ) (hρ : boxMem C1965189142x34Box ρ) :
    0 < (C1965189142x34Expr).evalReal ρ :=
  bb_sound C1965189142x34Tree C1965189142x34Box C1965189142x34_covers C1965189142x34_sub ρ hρ

#print axioms C1965189142x34_pos

end Kepler.Interval.Cases
