/-
  549 straddle BATCH pilot (auto-generated by
  pipeline/interval/emit_hull_pilot.py stageb-shards).
  case: 5490182221  (orig_op: <,
  vars: ['y1', 'y2', 'y3', 'y4', 'y5', 'y6'])
  Production HullD2 half: 40 C-side straddle_hull
  closed leaves, kernel `checkPosTMHull` (evalTMHullD2 df-hull
  composite), atan rungs open (128, -80) / closed
  (2048, -64).  40 PASS / 0 NEG;
  NEG leaf theorems state `= false` — kernel/compiled-run
  AGREEMENT checks, NOT certificates.
  Do not edit by hand.
-/
import Kepler.Interval.Cases.C549ArcSingleS1
import Kepler.Interval.Cases.C549ArcSingleS2

set_option maxHeartbeats 0

namespace Kepler.Interval.Cases

/-- Batch summary: the full leaf-property conjunction (the
shards state the same props; operands mirror the leaf props
and close with the shard theorems — no recomputation). -/
theorem C549ArcSingle_batch :
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box1 C549ArcSingleS1.P1 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box2 C549ArcSingleS1.P2 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box3 C549ArcSingleS1.P3 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box4 C549ArcSingleS1.P4 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box5 C549ArcSingleS1.P5 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box6 C549ArcSingleS1.P6 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box7 C549ArcSingleS1.P7 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box8 C549ArcSingleS1.P8 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box9 C549ArcSingleS1.P9 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box10 C549ArcSingleS1.P10 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box11 C549ArcSingleS1.P11 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box12 C549ArcSingleS1.P12 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box13 C549ArcSingleS1.P13 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box14 C549ArcSingleS1.P14 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box15 C549ArcSingleS1.P15 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box16 C549ArcSingleS1.P16 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box17 C549ArcSingleS1.P17 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box18 C549ArcSingleS1.P18 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box19 C549ArcSingleS1.P19 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS1.Box20 C549ArcSingleS1.P20 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box21 C549ArcSingleS2.P21 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box22 C549ArcSingleS2.P22 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box23 C549ArcSingleS2.P23 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box24 C549ArcSingleS2.P24 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box25 C549ArcSingleS2.P25 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box26 C549ArcSingleS2.P26 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box27 C549ArcSingleS2.P27 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box28 C549ArcSingleS2.P28 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box29 C549ArcSingleS2.P29 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box30 C549ArcSingleS2.P30 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box31 C549ArcSingleS2.P31 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box32 C549ArcSingleS2.P32 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box33 C549ArcSingleS2.P33 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box34 C549ArcSingleS2.P34 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box35 C549ArcSingleS2.P35 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box36 C549ArcSingleS2.P36 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box37 C549ArcSingleS2.P37 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box38 C549ArcSingleS2.P38 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box39 C549ArcSingleS2.P39 = true ∧
    checkPosTMHull C549ArcSingleExpr C549ArcSingleS2.Box40 C549ArcSingleS2.P40 = true :=
  ⟨C549ArcSingleS1.Leaf1, C549ArcSingleS1.Leaf2, C549ArcSingleS1.Leaf3, C549ArcSingleS1.Leaf4, C549ArcSingleS1.Leaf5, C549ArcSingleS1.Leaf6, C549ArcSingleS1.Leaf7, C549ArcSingleS1.Leaf8, C549ArcSingleS1.Leaf9, C549ArcSingleS1.Leaf10, C549ArcSingleS1.Leaf11, C549ArcSingleS1.Leaf12, C549ArcSingleS1.Leaf13, C549ArcSingleS1.Leaf14, C549ArcSingleS1.Leaf15, C549ArcSingleS1.Leaf16, C549ArcSingleS1.Leaf17, C549ArcSingleS1.Leaf18, C549ArcSingleS1.Leaf19, C549ArcSingleS1.Leaf20, C549ArcSingleS2.Leaf21, C549ArcSingleS2.Leaf22, C549ArcSingleS2.Leaf23, C549ArcSingleS2.Leaf24, C549ArcSingleS2.Leaf25, C549ArcSingleS2.Leaf26, C549ArcSingleS2.Leaf27, C549ArcSingleS2.Leaf28, C549ArcSingleS2.Leaf29, C549ArcSingleS2.Leaf30, C549ArcSingleS2.Leaf31, C549ArcSingleS2.Leaf32, C549ArcSingleS2.Leaf33, C549ArcSingleS2.Leaf34, C549ArcSingleS2.Leaf35, C549ArcSingleS2.Leaf36, C549ArcSingleS2.Leaf37, C549ArcSingleS2.Leaf38, C549ArcSingleS2.Leaf39, C549ArcSingleS2.Leaf40⟩

#print axioms C549ArcSingle_batch

end Kepler.Interval.Cases
