/-
  549 straddle BATCH pilot (auto-generated by
  pipeline/interval/emit_hull_pilot.py stageb-shards).
  case: 5490182221  (orig_op: <,
  vars: ['y1', 'y2', 'y3', 'y4', 'y5', 'y6'])
  Production HullD2 half: 40 C-side straddle_hull
  closed leaves, kernel `checkPosTMHull` (evalTMHullD2 df-hull
  composite), atan rungs open (128, -80) / closed
  (2048, -64).  40 PASS / 0 NEG;
  NEG leaf theorems state `= false` — kernel/compiled-run
  AGREEMENT checks, NOT certificates.
  Do not edit by hand.
-/
import Kepler.Interval.Cases.C549StraddleBatchSingleS1
import Kepler.Interval.Cases.C549StraddleBatchSingleS2

set_option maxHeartbeats 0

namespace Kepler.Interval.Cases

/-- Batch summary: the full leaf-property conjunction (the
shards state the same props; operands mirror the leaf props
and close with the shard theorems — no recomputation). -/
theorem C549StraddleBatchSingle_batch :
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box1 C549StraddleBatchSingleS1.P1 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box2 C549StraddleBatchSingleS1.P2 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box3 C549StraddleBatchSingleS1.P3 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box4 C549StraddleBatchSingleS1.P4 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box5 C549StraddleBatchSingleS1.P5 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box6 C549StraddleBatchSingleS1.P6 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box7 C549StraddleBatchSingleS1.P7 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box8 C549StraddleBatchSingleS1.P8 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box9 C549StraddleBatchSingleS1.P9 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box10 C549StraddleBatchSingleS1.P10 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box11 C549StraddleBatchSingleS1.P11 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box12 C549StraddleBatchSingleS1.P12 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box13 C549StraddleBatchSingleS1.P13 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box14 C549StraddleBatchSingleS1.P14 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box15 C549StraddleBatchSingleS1.P15 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box16 C549StraddleBatchSingleS1.P16 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box17 C549StraddleBatchSingleS1.P17 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box18 C549StraddleBatchSingleS1.P18 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box19 C549StraddleBatchSingleS1.P19 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS1.Box20 C549StraddleBatchSingleS1.P20 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box21 C549StraddleBatchSingleS2.P21 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box22 C549StraddleBatchSingleS2.P22 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box23 C549StraddleBatchSingleS2.P23 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box24 C549StraddleBatchSingleS2.P24 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box25 C549StraddleBatchSingleS2.P25 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box26 C549StraddleBatchSingleS2.P26 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box27 C549StraddleBatchSingleS2.P27 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box28 C549StraddleBatchSingleS2.P28 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box29 C549StraddleBatchSingleS2.P29 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box30 C549StraddleBatchSingleS2.P30 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box31 C549StraddleBatchSingleS2.P31 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box32 C549StraddleBatchSingleS2.P32 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box33 C549StraddleBatchSingleS2.P33 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box34 C549StraddleBatchSingleS2.P34 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box35 C549StraddleBatchSingleS2.P35 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box36 C549StraddleBatchSingleS2.P36 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box37 C549StraddleBatchSingleS2.P37 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box38 C549StraddleBatchSingleS2.P38 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box39 C549StraddleBatchSingleS2.P39 = true ∧
    checkPosTMHull C549StraddleBatchSingleExpr C549StraddleBatchSingleS2.Box40 C549StraddleBatchSingleS2.P40 = true :=
  ⟨C549StraddleBatchSingleS1.Leaf1, C549StraddleBatchSingleS1.Leaf2, C549StraddleBatchSingleS1.Leaf3, C549StraddleBatchSingleS1.Leaf4, C549StraddleBatchSingleS1.Leaf5, C549StraddleBatchSingleS1.Leaf6, C549StraddleBatchSingleS1.Leaf7, C549StraddleBatchSingleS1.Leaf8, C549StraddleBatchSingleS1.Leaf9, C549StraddleBatchSingleS1.Leaf10, C549StraddleBatchSingleS1.Leaf11, C549StraddleBatchSingleS1.Leaf12, C549StraddleBatchSingleS1.Leaf13, C549StraddleBatchSingleS1.Leaf14, C549StraddleBatchSingleS1.Leaf15, C549StraddleBatchSingleS1.Leaf16, C549StraddleBatchSingleS1.Leaf17, C549StraddleBatchSingleS1.Leaf18, C549StraddleBatchSingleS1.Leaf19, C549StraddleBatchSingleS1.Leaf20, C549StraddleBatchSingleS2.Leaf21, C549StraddleBatchSingleS2.Leaf22, C549StraddleBatchSingleS2.Leaf23, C549StraddleBatchSingleS2.Leaf24, C549StraddleBatchSingleS2.Leaf25, C549StraddleBatchSingleS2.Leaf26, C549StraddleBatchSingleS2.Leaf27, C549StraddleBatchSingleS2.Leaf28, C549StraddleBatchSingleS2.Leaf29, C549StraddleBatchSingleS2.Leaf30, C549StraddleBatchSingleS2.Leaf31, C549StraddleBatchSingleS2.Leaf32, C549StraddleBatchSingleS2.Leaf33, C549StraddleBatchSingleS2.Leaf34, C549StraddleBatchSingleS2.Leaf35, C549StraddleBatchSingleS2.Leaf36, C549StraddleBatchSingleS2.Leaf37, C549StraddleBatchSingleS2.Leaf38, C549StraddleBatchSingleS2.Leaf39, C549StraddleBatchSingleS2.Leaf40⟩

#print axioms C549StraddleBatchSingle_batch

end Kepler.Interval.Cases
