/-
  Phase 4, G4 certificate (auto-generated by pipeline/interval/emit_lean.py).
  case: SYNTH-DISJ-3  (orig_op: disj, vars: ['y1'])
  cert: 4 leaf/leaves, prec 64 (bb_arb)
  Do not edit by hand.
-/
import Kepler.Interval.CertBool

set_option maxHeartbeats 0

namespace Kepler.Interval.Cases

/-- The case expression (RPN prog mirrored as `IExpr`). -/
def Ccasexsynth3Expr : IExpr 1 :=
  (.sub (.var 0) (.const ⟨9, -2⟩))

/-- The target box (dyadic q-expansion of the original decimal box). -/
def Ccasexsynth3Box : Fin 1 → DInterval :=
  ![⟨⟨2, 0⟩, ⟨3, 0⟩⟩]

/-- The disjunctive goal list (main prog first). -/
def Ccasexsynth3Goals : List (DisjGoal 1) :=
  [(.pos (.sub (.var 0) (.const ⟨9, -2⟩))), (.pos (.sub (.const ⟨5, -1⟩) (.var 0)))]



/-- The certificate tree (leaf certs are inline kernel `decide`s). -/
def Ccasexsynth3Tree : BBTreeD 1 Ccasexsynth3Goals :=
  (.node ![⟨⟨2, 0⟩, ⟨3, 0⟩⟩] 0
  (.node ![⟨⟨2, 0⟩, ⟨5, -1⟩⟩] 0
    (.leaf ![⟨⟨2, 0⟩, ⟨9, -2⟩⟩] ⟨1, by decide⟩ (by decide))
    (.node ![⟨⟨9, -2⟩, ⟨5, -1⟩⟩] 0
      (.leaf ![⟨⟨9, -2⟩, ⟨19, -3⟩⟩] ⟨1, by decide⟩ (by decide))
      (.leaf ![⟨⟨19, -3⟩, ⟨5, -1⟩⟩] ⟨0, by decide⟩ (by decide))))
  (.leaf ![⟨⟨5, -1⟩, ⟨3, 0⟩⟩] ⟨0, by decide⟩ (by decide)))

/-- Covering of the whole tree, one kernel `decide`
through the Bool checker (`CertBool.coversB`). -/
theorem Ccasexsynth3_covers : Ccasexsynth3Tree.covers :=
  BBTreeD.coversB_sound _ (by decide)

/-- Box containment is reflexive here (tree root = target box). -/
theorem Ccasexsynth3_sub : boxSub Ccasexsynth3Box Ccasexsynth3Tree.box := by
  intro i
  fin_cases i <;> exact ⟨by decide, by decide⟩

/-- End-to-end: some disjunct holds at every point of the box. -/
theorem Ccasexsynth3_pos (ρ : Fin 1 → ℝ) (hρ : boxMem Ccasexsynth3Box ρ) :
    ∃ g ∈ Ccasexsynth3Goals, g.eval ρ :=
  bb_sound_disj Ccasexsynth3Tree Ccasexsynth3Box Ccasexsynth3_covers Ccasexsynth3_sub ρ hρ

#print axioms Ccasexsynth3_pos

end Kepler.Interval.Cases
