#!/usr/bin/env python3
"""Phase 4, G4: bb_arb cert JSON -> Lean certificate shards (arb-layer.md §4).

v1 scope (pilot): single-goal ("main") cases, ops
{push_var, push_const, add, sub, mul, neg, abs, div, ite};
dyadic consts inline, non-dyadic consts as exact `div` of int consts.
sqrt / trans (atan/sin/cos/ln) / disj goals are rejected for now:
- sqrt needs *per-leaf* mantissa certs (IExpr.sqrt bakes s₁ s₂ into the
  expression, but the radicand interval varies per leaf) — cert-layer
  extension pending;
- trans works in principle (fixed N/out across leaves) but is untested.

Usage: emit_lean.py <case.json> <cert.json> <out.lean> [--name NAME]
"""
import json
import sys


def die(msg):
    sys.exit(f"emit_lean: {msg}")


def dyadic(num, den):
    """num/den -> (m, e) with den = 2^-e, or None if not dyadic."""
    if den <= 0 or den & (den - 1):
        return None
    e = 0
    while den > 1:
        den >>= 1
        e -= 1
    return (num, e)


class RPN:
    """RPN prog -> IExpr text. Stack machine; each entry is a Lean term str."""

    def __init__(self, div_out=-64):
        self.div_out = div_out

    def const(self, c):
        num, den = c["num"], c["den"]
        d = dyadic(num, den)
        if d is not None:
            return f"(.const ⟨{d[0]}, {d[1]}⟩)"
        # non-dyadic rational: exact interval division of int consts
        return (f"(.div (.const ⟨{num}, 0⟩) (.const ⟨{den}, 0⟩) "
                f"({self.div_out}))")

    def emit(self, prog):
        st = []
        for ins in prog:
            if isinstance(ins, dict):
                if "ite" not in ins:
                    die(f"unknown dict instr {list(ins)}")
                c = self.emit(ins["ite"]["cond"])
                t = self.emit(ins["ite"]["then"])
                e = self.emit(ins["ite"]["else"])
                st.append(f"(.ite {c} {t} {e})")
                continue
            op = ins[0]
            if op == "push_var":
                st.append(f"(.var {ins[1]})")
            elif op == "push_const":
                st.append(self.const(ins[1]))
            elif op in ("add", "sub", "mul"):
                b, a = st.pop(), st.pop()
                st.append(f"(.{op} {a} {b})")
            elif op == "neg":
                st.append(f"(.neg {st.pop()})")
            elif op == "abs":
                st.append(f"(.abs {st.pop()})")
            elif op == "div":
                b, a = st.pop(), st.pop()
                st.append(f"(.div {a} {b} ({self.div_out}))")
            elif op in ("sqrt", "atan", "sin", "cos", "ln"):
                die(f"op {op}: not supported in v1 (see module docstring)")
            else:
                die(f"unknown op {op}")
        if len(st) != 1:
            die(f"RPN stack imbalance: {len(st)}")
        return st[0]


def box_lean(box):
    """JSON box [[{num,den},{num,den}],..] -> (Fin n -> DInterval) literal."""
    ivs = []
    for lo, hi in box:
        dlo, dhi = dyadic(lo["num"], lo["den"]), dyadic(hi["num"], hi["den"])
        if dlo is None or dhi is None:
            die("box endpoint not dyadic (expected q-expanded dyadic box)")
        ivs.append(f"⟨⟨{dlo[0]}, {dlo[1]}⟩, ⟨{dhi[0]}, {dhi[1]}⟩⟩")
    return "![" + ", ".join(ivs) + "]"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 3:
        die("usage: emit_lean.py <case.json> <cert.json> <out.lean>")
    case = json.load(open(args[0]))
    cert = json.load(open(args[1]))
    cid = args[0].split("/")[-1].replace(".json", "")
    mod = "C" + "".join(ch if ch.isalnum() else "x" for ch in cid)

    if case.get("disj"):
        die("disj case: v1 handles main-only certs (BBTreeD path pending)")
    hits = {l["hit"] for l in cert["leaves"]}
    if hits != {"main"}:
        die(f"cert hits {hits}: v1 main-only")
    if cert["root_box"] != case["box"]:
        die("cert root_box != case box")
    n = len(case["vars"])

    rpn = RPN()
    expr = rpn.emit(case["prog"])
    box = box_lean(case["box"])

    leaves = cert["leaves"]
    if len(leaves) == 1 and leaves[0]["box"] == case["box"]:
        tree, cert_thm, covers_thm = pilot_single_leaf(mod, box)
    else:
        die(f"{len(leaves)} leaves: tree emission not implemented in v1")

    out = f"""/-
  Phase 4, G4 certificate (auto-generated by pipeline/interval/emit_lean.py).
  case: {case['id']}  (orig_op: {case.get('orig_op')}, vars: {case['vars']})
  cert: {len(leaves)} leaf/leaves, prec {cert.get('prec')} (bb_arb)
  Do not edit by hand.
-/
import Kepler.Interval.Cert

namespace Kepler.Interval.Cases

/-- The case expression (RPN prog mirrored as `IExpr`). -/
def {mod}Expr : IExpr {n} :=
  {expr}

/-- The target box (dyadic q-expansion of the original decimal box). -/
def {mod}Box : Fin {n} → DInterval :=
  {box}

{cert_thm}

/-- The one-leaf certificate tree. -/
def {mod}Tree : BBTree {n} {mod}Expr :=
  {tree}

{covers_thm}

/-- Box containment is reflexive here (tree root = target box). -/
theorem {mod}_sub : boxSub {mod}Box {mod}Tree.box := by
  intro i
  fin_cases i <;> exact ⟨by decide, by decide⟩

/-- End-to-end: the case expression is strictly positive on the whole box. -/
theorem {mod}_pos (ρ : Fin {n} → ℝ) (hρ : boxMem {mod}Box ρ) :
    0 < ({mod}Expr).evalReal ρ :=
  bb_sound {mod}Tree {mod}Box {mod}_covers {mod}_sub ρ hρ

#print axioms {mod}_pos

end Kepler.Interval.Cases
"""
    open(args[2], "w").write(out)
    print(f"emit_lean: wrote {args[2]} (module Kepler.Interval.Cases.{mod})")


def pilot_single_leaf(mod, box):
    tree = f".leaf {mod}Box {mod}_cert"
    cert_thm = (f"/-- Whole-box positivity certificate (kernel `decide`). -/\n"
                f"theorem {mod}_cert : checkPos {mod}Expr {mod}Box = true := by\n"
                f"  decide")
    covers_thm = (f"/-- A single leaf trivially covers itself. -/\n"
                  f"theorem {mod}_covers : {mod}Tree.covers :=\n"
                  f"  trivial")
    return tree, cert_thm, covers_thm


if __name__ == "__main__":
    main()
