#!/usr/bin/env python3
"""TM1 probe generator: sample FAIL leaves from a repair chunk and emit a
TM-checker probe driver (auto-certificate hybrid Taylor-model evaluation,
VM-only measurement — no kernel involvement)."""
import os, sys

REPAIR_DIR = "lean/Kepler/Interval/Cases/Repair"
SRC = os.path.join(REPAIR_DIR, "CRepairBIXPCGWx7274157868xaW1R12_m64.d")
DST = os.path.join(REPAIR_DIR, "TM1ProbeBIXPCGW.d")
NSAMPLE = 150

def extract_defs(path, names):
    """Extract top-level `def NAME ... := <giant line>` blocks."""
    lines = open(path).read().splitlines(keepends=True)
    out = {}
    cur = None
    for ln in lines:
        if ln.startswith("def "):
            cur = None
            for nm in names:
                if ln.startswith(f"def {nm} "):
                    cur = nm
                    out[nm] = [ln]
                    break
            continue
        if cur is not None and (ln.startswith(" ") or ln.startswith("(")):
            out[cur].append(ln)
        elif cur is not None and not ln.strip():
            out[cur].append(ln)
        else:
            cur = None
    return out

def main():
    # verdicts
    fails = []
    for ln in open(os.path.join(SRC, "chunk00000.txt.out")):
        parts = ln.split()
        if len(parts) >= 2 and parts[1] == "FAIL":
            fails.append(int(parts[0]))
    print(f"FAIL leaves in chunk00000: {len(fails)}; sampling first {NSAMPLE}")
    fails = fails[:NSAMPLE]
    boxes = open(os.path.join(SRC, "chunk00000.txt")).read().splitlines()
    os.makedirs(DST, exist_ok=True)
    with open(os.path.join(DST, "boxes.txt"), "w") as f:
        for i in fails:
            f.write(boxes[i] + "\n")
    defs = extract_defs(os.path.join(SRC, "driver.lean"),
                        ["fillMkExpr0", "fillMkExpr1"])
    assert len(defs) == 2, defs.keys()
    driver = '''/-
  TM1 probe (auto-generated by pipeline/interval/tm1_probe_gen.py):
  Taylor-model pass rate on BIXPCGW repair round-1 FAIL leaves.
  VM-only measurement (stage-A mirror); no kernel checking.
-/
import Kepler.Interval.Tools.FillParams
import Kepler.Interval.CertTM

open Kepler.Interval Kepler.Interval.Tools

''' + "".join(defs["fillMkExpr0"]) + "\n" + "".join(defs["fillMkExpr1"]) + '''
namespace Kepler.Interval

/-- floor(sqrt(m * 2^(e mod 2))) — a valid `sqrtI` mantissa (VM-computed;
`Nat.sqrt` is exact). -/
def genSqrtCert (d : Dyadic) : Int :=
  if 0 ≤ d.m then ((d.m * 2 ^ (d.e % 2).toNat).toNat.sqrt : Int) else 0

/-- Auto sqrt certificate bundle from the sub-model (granularities picked so
`recipFloor` always has scaling room: `out ≤ -b.e`, precision ≥ 2⁻³²). -/
def genSqrtTMP {n : ℕ} (M : TaylorM n) : SqrtTMP :=
  let c := M.fB.lo.add (-M.W)
  let o1 := min (min (-(M.fB.lo.e / 2)) (-(M.fB.hi.e / 2))) (-32)
  let q8e := c.e + c.e / 2
  let o2 := min (-q8e) (-32)
  ⟨genSqrtCert M.fB.lo, genSqrtCert M.fB.hi, genSqrtCert c, o1, o2⟩

/-- Auto reciprocal certificate bundle (granularities only). -/
def genInvTMP {n : ℕ} (M : TaylorM n) : InvTMP :=
  let c := if (M.fB.lo.add (-M.W)).isPos then M.fB.lo.add (-M.W)
           else -(M.fB.hi.add M.W)
  let o0 := min (min (-M.fB.lo.e) (-M.fB.hi.e)) (-32)
  let o1 := min (min (-(c.e + c.e)) (-(M.fB.abs.hi.e + M.fB.abs.hi.e))) (-32)
  let o2 := min (-(c.e + c.e + c.e)) (-32)
  ⟨o0, o1, o2⟩

/-- Auto-certificate hybrid TM evaluation (mirror of `evalTMH` with the
certificate queues replaced by on-the-fly generation). -/
def evalTMHA {n : ℕ} (box : Fin n → DInterval) : IExpr n → Option (TaylorM n)
  | .const d => some (constTM box d)
  | .var k => some (varTM box k)
  | .neg e => (evalTMHA box e).map TaylorM.neg
  | .add e₁ e₂ =>
      (evalTMHA box e₁).bind fun M₁ => (evalTMHA box e₂).map fun M₂ => M₁.add M₂
  | .sub e₁ e₂ =>
      (evalTMHA box e₁).bind fun M₁ => (evalTMHA box e₂).map fun M₂ => M₁.sub M₂
  | .mul e₁ e₂ =>
      (evalTMHA box e₁).bind fun M₁ => (evalTMHA box e₂).map fun M₂ => M₁.mul M₂
  | .div e₁ e₂ out =>
      (evalTMHA box e₁).bind fun M₁ =>
      (evalTMHA box e₂).bind fun M₂ =>
      ((M₂.inv (genInvTMP M₂)).map fun Mi => M₁.mul Mi).orElse
        (fun _ => ((IExpr.div e₁ e₂ out).eval box).map (fallbackTM box))
  | .sqrt e s₁ s₂ =>
      (evalTMHA box e).bind fun M₀ =>
      ((M₀.sqrt (genSqrtTMP M₀)).orElse
        (fun _ => ((IExpr.sqrt e s₁ s₂).eval box).map (fallbackTM box)))
  | .abs e => ((IExpr.abs e).eval box).map (fallbackTM box)
  | .ite c t e => ((IExpr.ite c t e).eval box).map (fallbackTM box)
  | .trans k e N out => ((IExpr.trans k e N out).eval box).map (fallbackTM box)

/-- TM decision on one box (hybrid, auto certs): `some true` = closed. -/
def tmDecide {n : ℕ} (e : IExpr n) (box : Fin n → DInterval) : Bool :=
  match evalTMHA box e with
  | some M => (M.loBound box).isPos
  | none => false

end Kepler.Interval

def main : List String → IO UInt32
  | [path] => do
      let boxes ← readBoxes 7 path
      let e0 := fillMkExpr0 12 (-64)
      let e1 := fillMkExpr1 12 (-64)
      let mut pass := 0
      let mut fail := 0
      for i in [:boxes.size] do
        let b := boxes[i]!
        let ok := tmDecide e0 b || tmDecide e1 b
        if ok then pass := pass + 1 else fail := fail + 1
        IO.println s!"{i} {if ok then "TMPASS" else "TMFAIL"}"
      IO.println s!"TMRATE pass={pass} fail={fail} total={boxes.size}"
      return 0
  | _ => throw (IO.userError "usage: driver <boxes.txt>")
'''
    open(os.path.join(DST, "driver.lean"), "w").write(driver)
    print(f"probe written to {DST}")

if __name__ == "__main__":
    main()
