/-
Shard certificate for seed p=0 (Tri), UNTRUSTED data.
Generated by `pipeline/graphs/certgen.py` (emit_top, depth=4).
|top| = 6 nodes, |frontier| = 5 shard roots,
0 final nodes in the top.
-/
import Kepler.Graphs.TameEnum
import Kepler.Graphs.ArchiveData.Tri

namespace Kepler.Graphs

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Top nodes (BFS depth < 4); node 0 is `Seed 0`. -/
def TriTop : List Graph := [
  ⟨[⟨[0, 1, 2], true⟩, ⟨[2, 1, 0], false⟩], 3, [[⟨[0, 1, 2], true⟩, ⟨[2, 1, 0], false⟩], [⟨[0, 1, 2], true⟩, ⟨[2, 1, 0], false⟩], [⟨[0, 1, 2], true⟩, ⟨[2, 1, 0], false⟩]], [0, 0, 0]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 1, 0], false⟩], 4, [[⟨[0, 1, 2], true⟩, ⟨[3, 2, 1, 0], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[3, 2, 1, 0], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 1, 0], false⟩], [⟨[3, 2, 1, 0], false⟩, ⟨[0, 2, 3], true⟩]], [0, 0, 0, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1, 0, 3], false⟩], 5, [[⟨[0, 1, 2], true⟩, ⟨[4, 2, 1, 0, 3], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[4, 2, 1, 0, 3], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1, 0, 3], false⟩], [⟨[4, 2, 1, 0, 3], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[4, 2, 1, 0, 3], false⟩, ⟨[3, 2, 4], true⟩]], [0, 0, 0, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 1], true⟩, ⟨[1, 0, 3], false⟩], 4, [[⟨[0, 1, 2], true⟩, ⟨[1, 0, 3], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[3, 2, 1], true⟩, ⟨[1, 0, 3], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 1], true⟩], [⟨[1, 0, 3], false⟩, ⟨[3, 2, 1], true⟩, ⟨[0, 2, 3], true⟩]], [0, 0, 0, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 1, 0, 3, 4], false⟩], 6, [[⟨[0, 1, 2], true⟩, ⟨[5, 2, 1, 0, 3, 4], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[5, 2, 1, 0, 3, 4], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 1, 0, 3, 4], false⟩], [⟨[5, 2, 1, 0, 3, 4], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[5, 2, 1, 0, 3, 4], false⟩, ⟨[4, 2, 5], true⟩, ⟨[3, 2, 4], true⟩], [⟨[5, 2, 1, 0, 3, 4], false⟩, ⟨[4, 2, 5], true⟩]], [0, 0, 0, 1, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩, ⟨[1, 0, 3, 4], false⟩], 5, [[⟨[0, 1, 2], true⟩, ⟨[1, 0, 3, 4], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[4, 2, 1], true⟩, ⟨[1, 0, 3, 4], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩], [⟨[1, 0, 3, 4], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[1, 0, 3, 4], false⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 2, 4], true⟩]], [0, 0, 0, 1, 1]⟩
]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Per top node: children as (isFrontier, index) into
`TriFrontier` resp. `TriTop`. -/
def TriTopChildren : List (List (Bool × Nat)) := [
  [(false, 1)],
  [(false, 2), (false, 3)],
  [(false, 4), (false, 5)],
  [],
  [(true, 0), (true, 1)],
  [(true, 2), (true, 3), (true, 4)]
]

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 0 in
/-- Frontier nodes (BFS depth = 4); the shard roots. -/
def TriFrontier : List Graph := [
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 6], true⟩, ⟨[6, 2, 1, 0, 3, 4, 5], false⟩], 7, [[⟨[0, 1, 2], true⟩, ⟨[6, 2, 1, 0, 3, 4, 5], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[6, 2, 1, 0, 3, 4, 5], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 6], true⟩, ⟨[6, 2, 1, 0, 3, 4, 5], false⟩], [⟨[6, 2, 1, 0, 3, 4, 5], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[6, 2, 1, 0, 3, 4, 5], false⟩, ⟨[4, 2, 5], true⟩, ⟨[3, 2, 4], true⟩], [⟨[6, 2, 1, 0, 3, 4, 5], false⟩, ⟨[5, 2, 6], true⟩, ⟨[4, 2, 5], true⟩], [⟨[6, 2, 1, 0, 3, 4, 5], false⟩, ⟨[5, 2, 6], true⟩]], [0, 0, 0, 1, 1, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 1], true⟩, ⟨[1, 0, 3, 4, 5], false⟩], 6, [[⟨[0, 1, 2], true⟩, ⟨[1, 0, 3, 4, 5], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[5, 2, 1], true⟩, ⟨[1, 0, 3, 4, 5], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 5], true⟩, ⟨[5, 2, 1], true⟩], [⟨[1, 0, 3, 4, 5], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[1, 0, 3, 4, 5], false⟩, ⟨[4, 2, 5], true⟩, ⟨[3, 2, 4], true⟩], [⟨[1, 0, 3, 4, 5], false⟩, ⟨[5, 2, 1], true⟩, ⟨[4, 2, 5], true⟩]], [0, 0, 0, 1, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩, ⟨[4, 1, 5], true⟩, ⟨[5, 1, 0, 3, 4], false⟩], 6, [[⟨[0, 1, 2], true⟩, ⟨[5, 1, 0, 3, 4], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[4, 2, 1], true⟩, ⟨[4, 1, 5], true⟩, ⟨[5, 1, 0, 3, 4], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩], [⟨[5, 1, 0, 3, 4], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[5, 1, 0, 3, 4], false⟩, ⟨[4, 1, 5], true⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 2, 4], true⟩], [⟨[5, 1, 0, 3, 4], false⟩, ⟨[4, 1, 5], true⟩]], [0, 0, 0, 1, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩, ⟨[4, 1, 0], true⟩, ⟨[0, 3, 4], false⟩], 5, [[⟨[0, 1, 2], true⟩, ⟨[4, 1, 0], true⟩, ⟨[0, 3, 4], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[4, 2, 1], true⟩, ⟨[4, 1, 0], true⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩], [⟨[0, 3, 4], false⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 3, 4], false⟩, ⟨[4, 1, 0], true⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 2, 4], true⟩]], [0, 0, 0, 1, 1]⟩,
  ⟨[⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 4, 1], true⟩, ⟨[1, 0, 3], false⟩], 5, [[⟨[0, 1, 2], true⟩, ⟨[1, 0, 3], false⟩, ⟨[0, 2, 3], true⟩], [⟨[0, 1, 2], true⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 4, 1], true⟩, ⟨[1, 0, 3], false⟩], [⟨[0, 1, 2], true⟩, ⟨[0, 2, 3], true⟩, ⟨[3, 2, 4], true⟩, ⟨[4, 2, 1], true⟩], [⟨[1, 0, 3], false⟩, ⟨[3, 4, 1], true⟩, ⟨[3, 2, 4], true⟩, ⟨[0, 2, 3], true⟩], [⟨[3, 4, 1], true⟩, ⟨[4, 2, 1], true⟩, ⟨[3, 2, 4], true⟩]], [0, 0, 0, 1, 1]⟩
]

/-- (node index into `TriTop`, archive index into `TriData`)
for each final node in the top. 0 entries. -/
def TriTopFinals : List (Nat × Nat) := [

]

end Kepler.Graphs
