/-
Certificate checker for the tame plane graph enumeration (generic part).

Design: `docs/architecture.md` §"枚举树证书". The AFP's trie/worklist-based
`samet`/`tameEnumFilter` machinery (`ArchCompAux.thy`, `ArchCompProps.thy`,
`Computation/ArchComp.thy`, proved `by eval`) is NOT ported. Instead, each
seed p = 0..3 comes with an enumeration-tree certificate (untrusted,
generated by `pipeline/graphs/`): a list S of graph nodes such that

1. `Seed p ∈ S`;
2. S is closed under `next_tame p` (each node replayed in the kernel by
   `decide` — this is the only expensive step);
3. every final `g ∈ S` carries an isomorphism witness into the Archive.

Then `closure_mem` below gives: every graph reachable from `Seed p` via
`next_tame p` lies in S, hence every reachable final graph is isomorphic to
an Archive entry — the `same_p` hypotheses of `RelativeCompleteness.lean`.
-/
import Kepler.Graphs.TameEnumProps

namespace Kepler.Graphs

/-- Closure of a certified node set: anything reachable from `Seed p` via
`next_tame p` is in `S`, provided `S` contains `Seed p` and is closed under
`next_tame p`. -/
theorem closure_mem {p : Nat} (S : List Graph)
    (hseed : Seed p ∈ S)
    (hclosed : ∀ g ∈ S, ∀ g' ∈ next_tame p g, g' ∈ S)
    {g : Graph} (hr : RTranCl (next_tame p) (Seed p) g) : g ∈ S :=
  RTranCl_induct hr hseed hclosed

end Kepler.Graphs
