/-
AUTO-GENERATED certificate (sharded mode) — do not edit

Generated by `pipeline/lp/socert.py --shard-cols 1` from `pilot_204880136538_flat.lp`
(SoPlex exact rational mode, see `pipeline/lp/README.md`).

LP: max cᵀx s.t. A·x ≤ b, x ≥ 0 — 915 vars, 3882 rows.
Dual certificate: y = Y/D with D = certD, claimed bound γ = certG/certD.
Untrusted validation (exact Fraction arithmetic in the converter):
x ≥ 0, A·x ≤ b, y ≥ 0, Aᵀy ≥ c, cᵀx = bᵀy (strong duality).
-/
import Kepler.LP.Pilot204880136538.Data

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace Kepler.LP.Pilot204880136538

/-- Column shard 33: `AᵀY ≥ D·c` restricted to columns [33, 34). -/
theorem shard_33 : checkDualCols lp certY certD 33 1 = true := by
  decide

end Kepler.LP.Pilot204880136538
