/-
  Phase 4, G4 certificate (auto-generated by pipeline/interval/emit_lean.py).
  case: 3397113841  (orig_op: <, vars: ['y1', 'y2', 'y3', 'y4', 'y5', 'y6'])
  cert: 1504 leaf/leaves, prec 64 (bb_arb)
  Do not edit by hand.
-/
import Kepler.Interval.CertBool

namespace Kepler.Interval.Cases

/-- The case expression (RPN prog mirrored as `IExpr`). -/
def C3397113841Expr : IExpr 6 :=
  (.sub (.const ⟨0, 0⟩) (.add (.sub (.add (.add (.sub (.mul (.neg (.mul (.var 1) (.var 1))) (.mul (.var 2) (.var 2))) (.mul (.mul (.var 0) (.var 0)) (.mul (.var 3) (.var 3)))) (.mul (.mul (.var 1) (.var 1)) (.mul (.var 4) (.var 4)))) (.mul (.mul (.var 2) (.var 2)) (.mul (.var 5) (.var 5)))) (.mul (.mul (.var 4) (.var 4)) (.mul (.var 5) (.var 5)))) (.mul (.mul (.var 0) (.var 0)) (.add (.add (.sub (.add (.add (.neg (.mul (.var 0) (.var 0))) (.mul (.var 1) (.var 1))) (.mul (.var 2) (.var 2))) (.mul (.var 3) (.var 3))) (.mul (.var 4) (.var 4))) (.mul (.var 5) (.var 5))))))

/-- The target box (dyadic q-expansion of the original decimal box). -/
def C3397113841Box : Fin 6 → DInterval :=
  ![⟨⟨2, 0⟩, ⟨2705829397, -30⟩⟩, ⟨⟨2, 0⟩, ⟨2705829397, -30⟩⟩, ⟨⟨2, 0⟩, ⟨2705829397, -30⟩⟩, ⟨⟨225485783, -26⟩, ⟨3607772529, -30⟩⟩, ⟨⟨2, 0⟩, ⟨2705829397, -30⟩⟩, ⟨⟨2, 0⟩, ⟨2705829397, -30⟩⟩]

end Kepler.Interval.Cases
