/-
Kepler.Text.IneqClosureDefs — P6-E batch 1: the `sqrtdelta` rational family of
the 155-definition closure of the 993 Flyspeck nonlinear inequalities
(work order: `docs/ineq-closure-155.md`, generated by
`lean/scripts/closure155.py`).

Convention B ports: camelCase renames, each def carries its HOL anchor
(`/-- HOL \`name\` (file:line) -/`).  Dependencies already in Lean are reused,
not re-ported: `deltaX`/`deltaX4` (SphereKit), `lfun`/`h0` (PackingAuto2:461,
same body as sphere.hl:525).  Batch-1 enablers ported here because nothing
else provided them: `matan` and the argument permuters `rotate2`–`rotate6`.

Every def is followed by a correctness valve: `rfl` identity checks that pin
the argument permutations / definitional glue, plus closed-form numeric
spot-checks at the regular-tetrahedron point `x = (4,…,4)` (squared edge
lengths of the tetrahedron with all edges 2), where
`deltaX = 128`, `deltaX4 = 16`, `sqrt 16 = 4`, `sqrt 8 = 2√2` make the HOL
bodies evaluate in closed form.  The same sample values were recomputed from
the kepler-g4e `defs.json` ASTs (see docs/ineq-closure-155.md header).
-/

import Kepler.Text.SphereKit
import Kepler.Text.PackingAuto2

namespace Kepler.Text

/-! ## Enablers: `matan` and the `rotate2`–`rotate6` permuters (sphere.hl) -/

/-- HOL `matan` (sphere.hl:728-731): the modified arctangent, analytic
continuation of `ArcTan[Sqrt[x]]/Sqrt[x]`. -/
noncomputable def matan (x : ℝ) : ℝ :=
  if x = 0 then 1
  else if x > 0 then Real.arctan (Real.sqrt x) / Real.sqrt x
  else Real.log ((1 + Real.sqrt (-x)) / (1 - Real.sqrt (-x))) /
    (2 * Real.sqrt (-x))

/-- `matan` at the removable singularity. -/
example : matan 0 = 1 := by unfold matan; rw [if_pos rfl]

/-- Positive branch, `x = 1`: `atn(1)/1 = π/4`. -/
example : matan 1 = Real.pi / 4 := by
  unfold matan
  rw [if_neg (by norm_num), if_pos (by norm_num), Real.sqrt_one,
    Real.arctan_one, div_one]

/-- Negative branch, `x = -1`: `(1+1)/(1-1) = 2/0 = 0`, so `log 0 = 0` and the
whole quotient is `0` (junk-value semantics; pins the `--x` translation). -/
example : matan (-1) = 0 := by
  unfold matan
  rw [if_neg (by norm_num), if_neg (by norm_num)]
  norm_num [Real.log_zero]

/-- The positive branch really is `arctan(√x)/√x` (catches a flipped
numerator/denominator). -/
example {x : ℝ} (hx : 0 < x) :
    matan x * Real.sqrt x = Real.arctan (Real.sqrt x) := by
  unfold matan
  rw [if_neg (ne_of_gt hx), if_pos hx]
  exact div_mul_cancel₀ _ (Real.sqrt_ne_zero'.mpr hx)

/-- HOL `rotate2` (sphere.hl:654-655). -/
def rotate2 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x2 x3 x1 x5 x6 x4

/-- HOL `rotate3` (sphere.hl:657-658). -/
def rotate3 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x3 x1 x2 x6 x4 x5

/-- HOL `rotate4` (sphere.hl:660-661). -/
def rotate4 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x4 x2 x6 x1 x5 x3

/-- HOL `rotate5` (sphere.hl:663-664). -/
def rotate5 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x5 x3 x4 x2 x6 x1

/-- HOL `rotate6` (sphere.hl:666-667). -/
def rotate6 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x6 x1 x5 x3 x4 x2

/-- `rotate2`/`rotate3` are inverse 3-cycles on the argument triples
`(x1 x2 x3)` and `(x4 x5 x6)` — pins both permutation tables at once. -/
example : rotate2 (rotate3 f) x1 x2 x3 x4 x5 x6 = f x1 x2 x3 x4 x5 x6 := rfl

/-- Two `rotate2`s make one `rotate3`. -/
example : rotate2 (rotate2 f) x1 x2 x3 x4 x5 x6 = rotate3 f x1 x2 x3 x4 x5 x6 :=
  rfl

/-! ## Batch 1: the `sqrtdelta` rational family (nonlin_def.hl) -/

/-- HOL `dih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:138-142): a valid
formula for `dih_x / sqrt(delta_x)` when `delta_x > 0` and
`delta_x4 ≠ 0`; "posbranch" = no `pi_shift` term (the `d_x4 ≥ 0` branch of
`dih_x_div_sqrtdelta`, nonlin_def.hl:132). -/
noncomputable def dihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let dX4 := deltaX4 x1 x2 x3 x4 x5 x6
  let d := deltaX x1 x2 x3 x4 x5 x6
  (Real.sqrt (4 * x1) / dX4) * matan (4 * x1 * d / dX4 ^ 2)

/-- Regular-tetrahedron spot-check: at `x = (4,…,4)`,
`deltaX = 128`, `deltaX4 = 16`, so the body is
`sqrt(16)/16 * matan(16*128/256) = matan(8)/4 = arctan(2√2)/(8√2)`
(the HOL-side value, since `matan 8 = atn(√8)/√8`). -/
example : dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    Real.arctan (2 * Real.sqrt 2) / (8 * Real.sqrt 2) := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have h16 : deltaX4 4 4 4 4 4 4 = 16 := by norm_num [deltaX4]
  have hs16 : Real.sqrt (16 : ℝ) = 4 := by
    rw [show (16 : ℝ) = 4 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs8 : Real.sqrt (8 : ℝ) = 2 * Real.sqrt 2 := by
    rw [show (8 : ℝ) = 2 ^ 2 * 2 by norm_num, Real.sqrt_mul (by norm_num),
      Real.sqrt_sq (by norm_num)]
  have hs2 : Real.sqrt (2 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  unfold dihXDivSqrtdeltaPosbranch
  rw [h128, h16]
  show Real.sqrt (4 * 4) / 16 * matan (4 * 4 * 128 / 16 ^ 2) = _
  unfold matan
  rw [show (4 : ℝ) * 4 * 128 / 16 ^ 2 = 8 by norm_num,
    if_neg (show ¬(8 : ℝ) = 0 by norm_num),
    if_pos (show (0 : ℝ) < 8 by norm_num),
    show (4 : ℝ) * 4 = 16 by norm_num, hs16, hs8]
  field_simp
  ring

/-- HOL `dih4_x_div_sqrtdelta_posbranch` (nonlin_def.hl:163-164):
`rotate4 dih_x_div_sqrtdelta_posbranch` (η-expanded). -/
noncomputable def dih4XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate4` argument order for this instance. -/
example : dih4XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    dihXDivSqrtdeltaPosbranch x4 x2 x6 x1 x5 x3 := rfl

/-- HOL `ldih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:144-146); the HOL
`lfun` (sphere.hl:525) is `Kepler.Text.lfun` (PackingAuto2.lean:461). -/
noncomputable def ldihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  lfun (Real.sqrt x1 / 2) * dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Spot-check: at `x = (4,…,4)`, `lfun (sqrt 4 / 2) = lfun 1 = 1`, so `ldih`
collapses to `dih`. -/
example : ldihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 := by
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold ldihXDivSqrtdeltaPosbranch
  rw [hs4]
  norm_num [lfun, h0]

/-- HOL `ldih2_x_div_sqrtdelta_posbranch` (nonlin_def.hl:148-149). -/
noncomputable def ldih2XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate2 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih3_x_div_sqrtdelta_posbranch` (nonlin_def.hl:151-152). -/
noncomputable def ldih3XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate3 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih5_x_div_sqrtdelta_posbranch` (nonlin_def.hl:154-155). -/
noncomputable def ldih5XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih6_x_div_sqrtdelta_posbranch` (nonlin_def.hl:157-158). -/
noncomputable def ldih6XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate2` instance (others follow from the generic `rotate`
checks above). -/
example : ldih2XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    ldihXDivSqrtdeltaPosbranch x2 x3 x1 x5 x6 x4 := rfl

/-- HOL `sol_euler_x_div_sqrtdelta` (nonlin_def.hl:115-119). Valid when the
let-bound `a > 0`; `a` is verbatim the body of `eulerA_x`
(sphere.hl:830-833). -/
noncomputable def solEulerXDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let a := Real.sqrt (x1 * x2 * x3) + Real.sqrt x1 * (x2 + x3 - x4) / 2 +
    Real.sqrt x2 * (x1 + x3 - x5) / 2 + Real.sqrt x3 * (x1 + x2 - x6) / 2
  matan (deltaX x1 x2 x3 x4 x5 x6 / (4 * a ^ 2)) / a

/-- Regular-tetrahedron spot-check: `a = 8 + 4 + 4 + 4 = 20`,
`deltaX = 128`, so the value is `matan(128/1600)/20 = matan(2/25)/20`. -/
example : solEulerXDivSqrtdelta 4 4 4 4 4 4 = matan (2 / 25) / 20 := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have hs64 : Real.sqrt ((4 : ℝ) * 4 * 4) = 8 := by
    rw [show (4 : ℝ) * 4 * 4 = 8 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold solEulerXDivSqrtdelta
  norm_num [h128, hs64, hs4]

/-- HOL `sol_euler246_x_div_sqrtdelta` (nonlin_def.hl:121-122):
`rotate4 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler246XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler345_x_div_sqrtdelta` (nonlin_def.hl:124-125):
`rotate5 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler345XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler156_x_div_sqrtdelta` (nonlin_def.hl:127-128):
`rotate6 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler156XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- Pins the `rotate6` instance against the base definition. -/
example : solEuler156XDivSqrtdelta x1 x2 x3 x4 x5 x6 =
    solEulerXDivSqrtdelta x6 x1 x5 x3 x4 x2 := rfl

/-- HOL `delta4_squared_x` (sphere.hl:835-836). -/
noncomputable def delta4SquaredX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  deltaX4 x1 x2 x3 x4 x5 x6 ^ 2

/-- Numeric spot-check: `deltaX4 (4,…,4) = 16`, squared is 256 (pins `pow 2`
as a real square). -/
example : delta4SquaredX 4 4 4 4 4 4 = 256 := by
  norm_num [delta4SquaredX, deltaX4]

/-! ## Batch 2: the 6-ary operator calculus (nonlin_def.hl)

LocalAuto19.lean:59-60 *collapses* this calculus (`uni`/`mul6`/`compose6`/
`constant6`/`proj_*`/`dummy6`) into x-level statements; per the P6-E batch-2
decision the operators are ported as real defs here instead, so the G4
interval pipeline can glue on `rfl`-mirrors of these bodies.  The collapse is
propositionally invisible at the x-level (e.g. `mk126 f x1 … x6 = f x1 x2 2 2
2 x6` below holds by `rfl`), so no semantic divergence is introduced — the
difference is only which side carries the composite structure.

HOL `proj_xi` (nonlin_def.hl:40-50) are polymorphic (`(x1:A) (x2:B) …`);
only the ℝ⁶ → ℝ instances used by the closure are ported.  HOL `norm2hh`
reuses PackingAuto2's `hminus` (the `Classical.epsilon` rendering of the
`@x.` choice, PackingAuto2.lean:468) and `hplus` (= 1.3254). -/

/-- HOL `proj_x1` (nonlin_def.hl:40). -/
def projX1 (x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := x1

/-- HOL `proj_x2` (nonlin_def.hl:42). -/
def projX2 (_x1 x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := x2

/-- HOL `proj_x3` (nonlin_def.hl:44). -/
def projX3 (_x1 _x2 x3 _x4 _x5 _x6 : ℝ) : ℝ := x3

/-- HOL `proj_x4` (nonlin_def.hl:46). -/
def projX4 (_x1 _x2 _x3 x4 _x5 _x6 : ℝ) : ℝ := x4

/-- HOL `proj_x5` (nonlin_def.hl:48). -/
def projX5 (_x1 _x2 _x3 _x4 x5 _x6 : ℝ) : ℝ := x5

/-- HOL `proj_x6` (nonlin_def.hl:50). -/
def projX6 (_x1 _x2 _x3 _x4 _x5 x6 : ℝ) : ℝ := x6

example : projX2 1 2 3 4 5 6 = 2 := rfl

example : projX6 1 2 3 4 5 6 = 6 := rfl

/-- HOL `proj_y4` (nonlin_def.hl:300-301): the y-coordinate projection,
`sqrt x4`. -/
noncomputable def projY4 (_x1 _x2 _x3 x4 _x5 _x6 : ℝ) : ℝ := Real.sqrt x4

/-- HOL `proj_y5` (nonlin_def.hl:303-304). -/
noncomputable def projY5 (_x1 _x2 _x3 _x4 x5 _x6 : ℝ) : ℝ := Real.sqrt x5

/-- HOL `proj_y6` (nonlin_def.hl:306-307). -/
noncomputable def projY6 (_x1 _x2 _x3 _x4 _x5 x6 : ℝ) : ℝ := Real.sqrt x6

/-- Numeric: `projY4` at squared inputs picks up the unsquared coordinate. -/
example : projY4 1 4 9 16 25 36 = 4 := by
  unfold projY4
  rw [show (16 : ℝ) = 4 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

example : projY6 1 4 9 16 25 36 = 6 := by
  unfold projY6
  rw [show (36 : ℝ) = 6 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

/-- HOL `constant6` (nonlin_def.hl:249). -/
def constant6 (c : ℝ) (_x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := c

/-- HOL `two6` (nonlin_def.hl:259): `constant6 (&2)`. -/
def two6 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ := constant6 2

example : two6 1 2 3 4 5 6 = 2 := rfl

/-- HOL `compose6` (nonlin_def.hl:72-80). NB: defs.json's `body_ast` for this
def is a truncated parse artifact (`{"const":"f"}`); the HOL source above is
the authority and is what is ported here. -/
def compose6 (f p1 p2 p3 p4 p5 p6 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  f (p1 x1 x2 x3 x4 x5 x6) (p2 x1 x2 x3 x4 x5 x6) (p3 x1 x2 x3 x4 x5 x6)
    (p4 x1 x2 x3 x4 x5 x6) (p5 x1 x2 x3 x4 x5 x6) (p6 x1 x2 x3 x4 x5 x6)

/-- HOL `mk_126` (nonlin_def.hl:267-268). -/
def mk126 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f projX1 projX2 two6 two6 two6 projX6

/-- HOL `mk_456` (nonlin_def.hl:270-271). -/
def mk456 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f two6 two6 two6 projX4 projX5 projX6

/-- HOL `mk_135` (nonlin_def.hl:273-274). -/
def mk135 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f projX1 two6 projX3 two6 projX5 two6

/-- Pins the whole `compose6`/`proj`/`two6` stack for `mk_126`:
setting the 3/4/5 slots to the constant 2. -/
example : mk126 f x1 x2 x3 x4 x5 x6 = f x1 x2 2 2 2 x6 := rfl

example : mk135 f x1 x2 x3 x4 x5 x6 = f x1 2 x3 2 x5 2 := rfl

example : mk456 f x1 x2 x3 x4 x5 x6 = f 2 2 2 x4 x5 x6 := rfl

/-- HOL `promote1_to_6` (nonlin_def.hl:254-255). -/
def promote1To6 (f : ℝ → ℝ) (x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := f x1

/-- HOL `promote3_to_6` (nonlin_def.hl:251-252). -/
def promote3To6 (f : ℝ → ℝ → ℝ → ℝ) (x1 x2 x3 _x4 _x5 _x6 : ℝ) : ℝ := f x1 x2 x3

example : promote1To6 f x1 x2 x3 x4 x5 x6 = f x1 := rfl

/-- Numeric: promotes a unary function onto the first slot. -/
example : promote1To6 Real.sqrt 9 0 0 0 0 0 = 3 := by
  unfold promote1To6
  rw [show (9 : ℝ) = 3 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

example : promote3To6 (fun a b c => a + b + c) 1 2 3 4 5 6 = 6 := by
  norm_num [promote3To6]

/-- HOL `scalar6` (nonlin_def.hl:279-280). -/
def scalar6 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) (r : ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x1 x2 x3 x4 x5 x6 * r

example : scalar6 f r x1 x2 x3 x4 x5 x6 = f x1 x2 x3 x4 x5 x6 * r := rfl

/-- Numeric: `scalar6 two6 3` is the constant 6. -/
example : scalar6 two6 3 1 1 1 1 1 1 = 6 := by norm_num [scalar6, two6, constant6]

/-- HOL `norm2hh` (sphere.hl:597-599). -/
noncomputable def norm2hh (y1 y2 y3 y4 y5 y6 : ℝ) : ℝ :=
  (y1 - hminus - hplus) ^ 2 + (y2 - 2) ^ 2 + (y3 - 2) ^ 2 + (y4 - 2) ^ 2 +
    (y5 - 2) ^ 2 + (y6 - 2) ^ 2

/-- Numeric: vanishes at the center `(hminus + hplus, 2,…,2)` — pins the
left-associated `y1 - hminus - hplus` grouping and the five `(yi - 2)²`. -/
example : norm2hh (hminus + hplus) 2 2 2 2 2 = 0 := by unfold norm2hh; ring

/-- Numeric: one unit off center in `y1` gives 1. -/
example : norm2hh (hminus + hplus + 1) 2 2 2 2 2 = 1 := by
  unfold norm2hh; ring

/-! ## Axiom audit (standard three only: propext / Classical.choice /
Quot.sound) -/

#print axioms dihXDivSqrtdeltaPosbranch
#print axioms ldih6XDivSqrtdeltaPosbranch
#print axioms solEulerXDivSqrtdelta
#print axioms solEuler156XDivSqrtdelta
#print axioms delta4SquaredX
#print axioms matan
#print axioms compose6
#print axioms mk126
#print axioms norm2hh

end Kepler.Text
