/-
Kepler.Text.IneqClosureDefs — P6-E batch 1: the `sqrtdelta` rational family of
the 155-definition closure of the 993 Flyspeck nonlinear inequalities
(work order: `docs/ineq-closure-155.md`, generated by
`lean/scripts/closure155.py`).

Convention B ports: camelCase renames, each def carries its HOL anchor
(`/-- HOL \`name\` (file:line) -/`).  Dependencies already in Lean are reused,
not re-ported: `deltaX`/`deltaX4` (SphereKit), `lfun`/`h0` (PackingAuto2:461,
same body as sphere.hl:525).  Batch-1 enablers ported here because nothing
else provided them: `matan` and the argument permuters `rotate2`–`rotate6`.

Every def is followed by a correctness valve: `rfl` identity checks that pin
the argument permutations / definitional glue, plus closed-form numeric
spot-checks at the regular-tetrahedron point `x = (4,…,4)` (squared edge
lengths of the tetrahedron with all edges 2), where
`deltaX = 128`, `deltaX4 = 16`, `sqrt 16 = 4`, `sqrt 8 = 2√2` make the HOL
bodies evaluate in closed form.  The same sample values were recomputed from
the kepler-g4e `defs.json` ASTs (see docs/ineq-closure-155.md header).
-/

import Kepler.Text.SphereKit
import Kepler.Text.PackingAuto2

namespace Kepler.Text

/-! ## Enablers: `matan` and the `rotate2`–`rotate6` permuters (sphere.hl) -/

/-- HOL `matan` (sphere.hl:728-731): the modified arctangent, analytic
continuation of `ArcTan[Sqrt[x]]/Sqrt[x]`. -/
noncomputable def matan (x : ℝ) : ℝ :=
  if x = 0 then 1
  else if x > 0 then Real.arctan (Real.sqrt x) / Real.sqrt x
  else Real.log ((1 + Real.sqrt (-x)) / (1 - Real.sqrt (-x))) /
    (2 * Real.sqrt (-x))

/-- `matan` at the removable singularity. -/
example : matan 0 = 1 := by unfold matan; rw [if_pos rfl]

/-- Positive branch, `x = 1`: `atn(1)/1 = π/4`. -/
example : matan 1 = Real.pi / 4 := by
  unfold matan
  rw [if_neg (by norm_num), if_pos (by norm_num), Real.sqrt_one,
    Real.arctan_one, div_one]

/-- Negative branch, `x = -1`: `(1+1)/(1-1) = 2/0 = 0`, so `log 0 = 0` and the
whole quotient is `0` (junk-value semantics; pins the `--x` translation). -/
example : matan (-1) = 0 := by
  unfold matan
  rw [if_neg (by norm_num), if_neg (by norm_num)]
  norm_num [Real.log_zero]

/-- The positive branch really is `arctan(√x)/√x` (catches a flipped
numerator/denominator). -/
example {x : ℝ} (hx : 0 < x) :
    matan x * Real.sqrt x = Real.arctan (Real.sqrt x) := by
  unfold matan
  rw [if_neg (ne_of_gt hx), if_pos hx]
  exact div_mul_cancel₀ _ (Real.sqrt_ne_zero'.mpr hx)

/-- HOL `rotate2` (sphere.hl:654-655). -/
def rotate2 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x2 x3 x1 x5 x6 x4

/-- HOL `rotate3` (sphere.hl:657-658). -/
def rotate3 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x3 x1 x2 x6 x4 x5

/-- HOL `rotate4` (sphere.hl:660-661). -/
def rotate4 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x4 x2 x6 x1 x5 x3

/-- HOL `rotate5` (sphere.hl:663-664). -/
def rotate5 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x5 x3 x4 x2 x6 x1

/-- HOL `rotate6` (sphere.hl:666-667). -/
def rotate6 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x6 x1 x5 x3 x4 x2

/-- `rotate2`/`rotate3` are inverse 3-cycles on the argument triples
`(x1 x2 x3)` and `(x4 x5 x6)` — pins both permutation tables at once. -/
example : rotate2 (rotate3 f) x1 x2 x3 x4 x5 x6 = f x1 x2 x3 x4 x5 x6 := rfl

/-- Two `rotate2`s make one `rotate3`. -/
example : rotate2 (rotate2 f) x1 x2 x3 x4 x5 x6 = rotate3 f x1 x2 x3 x4 x5 x6 :=
  rfl

/-! ## Batch 1: the `sqrtdelta` rational family (nonlin_def.hl) -/

/-- HOL `dih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:138-142): a valid
formula for `dih_x / sqrt(delta_x)` when `delta_x > 0` and
`delta_x4 ≠ 0`; "posbranch" = no `pi_shift` term (the `d_x4 ≥ 0` branch of
`dih_x_div_sqrtdelta`, nonlin_def.hl:132). -/
noncomputable def dihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let dX4 := deltaX4 x1 x2 x3 x4 x5 x6
  let d := deltaX x1 x2 x3 x4 x5 x6
  (Real.sqrt (4 * x1) / dX4) * matan (4 * x1 * d / dX4 ^ 2)

/-- Regular-tetrahedron spot-check: at `x = (4,…,4)`,
`deltaX = 128`, `deltaX4 = 16`, so the body is
`sqrt(16)/16 * matan(16*128/256) = matan(8)/4 = arctan(2√2)/(8√2)`
(the HOL-side value, since `matan 8 = atn(√8)/√8`). -/
example : dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    Real.arctan (2 * Real.sqrt 2) / (8 * Real.sqrt 2) := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have h16 : deltaX4 4 4 4 4 4 4 = 16 := by norm_num [deltaX4]
  have hs16 : Real.sqrt (16 : ℝ) = 4 := by
    rw [show (16 : ℝ) = 4 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs8 : Real.sqrt (8 : ℝ) = 2 * Real.sqrt 2 := by
    rw [show (8 : ℝ) = 2 ^ 2 * 2 by norm_num, Real.sqrt_mul (by norm_num),
      Real.sqrt_sq (by norm_num)]
  have hs2 : Real.sqrt (2 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  unfold dihXDivSqrtdeltaPosbranch
  rw [h128, h16]
  show Real.sqrt (4 * 4) / 16 * matan (4 * 4 * 128 / 16 ^ 2) = _
  unfold matan
  rw [show (4 : ℝ) * 4 * 128 / 16 ^ 2 = 8 by norm_num,
    if_neg (show ¬(8 : ℝ) = 0 by norm_num),
    if_pos (show (0 : ℝ) < 8 by norm_num),
    show (4 : ℝ) * 4 = 16 by norm_num, hs16, hs8]
  field_simp
  ring

/-- HOL `dih4_x_div_sqrtdelta_posbranch` (nonlin_def.hl:163-164):
`rotate4 dih_x_div_sqrtdelta_posbranch` (η-expanded). -/
noncomputable def dih4XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate4` argument order for this instance. -/
example : dih4XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    dihXDivSqrtdeltaPosbranch x4 x2 x6 x1 x5 x3 := rfl

/-- HOL `ldih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:144-146); the HOL
`lfun` (sphere.hl:525) is `Kepler.Text.lfun` (PackingAuto2.lean:461). -/
noncomputable def ldihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  lfun (Real.sqrt x1 / 2) * dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Spot-check: at `x = (4,…,4)`, `lfun (sqrt 4 / 2) = lfun 1 = 1`, so `ldih`
collapses to `dih`. -/
example : ldihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 := by
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold ldihXDivSqrtdeltaPosbranch
  rw [hs4]
  norm_num [lfun, h0]

/-- HOL `ldih2_x_div_sqrtdelta_posbranch` (nonlin_def.hl:148-149). -/
noncomputable def ldih2XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate2 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih3_x_div_sqrtdelta_posbranch` (nonlin_def.hl:151-152). -/
noncomputable def ldih3XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate3 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih5_x_div_sqrtdelta_posbranch` (nonlin_def.hl:154-155). -/
noncomputable def ldih5XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih6_x_div_sqrtdelta_posbranch` (nonlin_def.hl:157-158). -/
noncomputable def ldih6XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate2` instance (others follow from the generic `rotate`
checks above). -/
example : ldih2XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    ldihXDivSqrtdeltaPosbranch x2 x3 x1 x5 x6 x4 := rfl

/-- HOL `sol_euler_x_div_sqrtdelta` (nonlin_def.hl:115-119). Valid when the
let-bound `a > 0`; `a` is verbatim the body of `eulerA_x`
(sphere.hl:830-833). -/
noncomputable def solEulerXDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let a := Real.sqrt (x1 * x2 * x3) + Real.sqrt x1 * (x2 + x3 - x4) / 2 +
    Real.sqrt x2 * (x1 + x3 - x5) / 2 + Real.sqrt x3 * (x1 + x2 - x6) / 2
  matan (deltaX x1 x2 x3 x4 x5 x6 / (4 * a ^ 2)) / a

/-- Regular-tetrahedron spot-check: `a = 8 + 4 + 4 + 4 = 20`,
`deltaX = 128`, so the value is `matan(128/1600)/20 = matan(2/25)/20`. -/
example : solEulerXDivSqrtdelta 4 4 4 4 4 4 = matan (2 / 25) / 20 := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have hs64 : Real.sqrt ((4 : ℝ) * 4 * 4) = 8 := by
    rw [show (4 : ℝ) * 4 * 4 = 8 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold solEulerXDivSqrtdelta
  norm_num [h128, hs64, hs4]

/-- HOL `sol_euler246_x_div_sqrtdelta` (nonlin_def.hl:121-122):
`rotate4 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler246XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler345_x_div_sqrtdelta` (nonlin_def.hl:124-125):
`rotate5 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler345XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler156_x_div_sqrtdelta` (nonlin_def.hl:127-128):
`rotate6 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler156XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- Pins the `rotate6` instance against the base definition. -/
example : solEuler156XDivSqrtdelta x1 x2 x3 x4 x5 x6 =
    solEulerXDivSqrtdelta x6 x1 x5 x3 x4 x2 := rfl

/-- HOL `delta4_squared_x` (sphere.hl:835-836). -/
noncomputable def delta4SquaredX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  deltaX4 x1 x2 x3 x4 x5 x6 ^ 2

/-- Numeric spot-check: `deltaX4 (4,…,4) = 16`, squared is 256 (pins `pow 2`
as a real square). -/
example : delta4SquaredX 4 4 4 4 4 4 = 256 := by
  norm_num [delta4SquaredX, deltaX4]

/-! ## Batch 2: the 6-ary operator calculus (nonlin_def.hl)

LocalAuto19.lean:59-60 *collapses* this calculus (`uni`/`mul6`/`compose6`/
`constant6`/`proj_*`/`dummy6`) into x-level statements; per the P6-E batch-2
decision the operators are ported as real defs here instead, so the G4
interval pipeline can glue on `rfl`-mirrors of these bodies.  The collapse is
propositionally invisible at the x-level (e.g. `mk126 f x1 … x6 = f x1 x2 2 2
2 x6` below holds by `rfl`), so no semantic divergence is introduced — the
difference is only which side carries the composite structure.

HOL `proj_xi` (nonlin_def.hl:40-50) are polymorphic (`(x1:A) (x2:B) …`);
only the ℝ⁶ → ℝ instances used by the closure are ported.  HOL `norm2hh`
reuses PackingAuto2's `hminus` (the `Classical.epsilon` rendering of the
`@x.` choice, PackingAuto2.lean:468) and `hplus` (= 1.3254). -/

/-- HOL `proj_x1` (nonlin_def.hl:40). -/
def projX1 (x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := x1

/-- HOL `proj_x2` (nonlin_def.hl:42). -/
def projX2 (_x1 x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := x2

/-- HOL `proj_x3` (nonlin_def.hl:44). -/
def projX3 (_x1 _x2 x3 _x4 _x5 _x6 : ℝ) : ℝ := x3

/-- HOL `proj_x4` (nonlin_def.hl:46). -/
def projX4 (_x1 _x2 _x3 x4 _x5 _x6 : ℝ) : ℝ := x4

/-- HOL `proj_x5` (nonlin_def.hl:48). -/
def projX5 (_x1 _x2 _x3 _x4 x5 _x6 : ℝ) : ℝ := x5

/-- HOL `proj_x6` (nonlin_def.hl:50). -/
def projX6 (_x1 _x2 _x3 _x4 _x5 x6 : ℝ) : ℝ := x6

example : projX2 1 2 3 4 5 6 = 2 := rfl

example : projX6 1 2 3 4 5 6 = 6 := rfl

/-- HOL `proj_y4` (nonlin_def.hl:300-301): the y-coordinate projection,
`sqrt x4`. -/
noncomputable def projY4 (_x1 _x2 _x3 x4 _x5 _x6 : ℝ) : ℝ := Real.sqrt x4

/-- HOL `proj_y5` (nonlin_def.hl:303-304). -/
noncomputable def projY5 (_x1 _x2 _x3 _x4 x5 _x6 : ℝ) : ℝ := Real.sqrt x5

/-- HOL `proj_y6` (nonlin_def.hl:306-307). -/
noncomputable def projY6 (_x1 _x2 _x3 _x4 _x5 x6 : ℝ) : ℝ := Real.sqrt x6

/-- Numeric: `projY4` at squared inputs picks up the unsquared coordinate. -/
example : projY4 1 4 9 16 25 36 = 4 := by
  unfold projY4
  rw [show (16 : ℝ) = 4 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

example : projY6 1 4 9 16 25 36 = 6 := by
  unfold projY6
  rw [show (36 : ℝ) = 6 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

/-- HOL `constant6` (nonlin_def.hl:249). -/
def constant6 (c : ℝ) (_x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := c

/-- HOL `two6` (nonlin_def.hl:259): `constant6 (&2)`. -/
def two6 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ := constant6 2

example : two6 1 2 3 4 5 6 = 2 := rfl

/-- HOL `compose6` (nonlin_def.hl:72-80). NB: defs.json's `body_ast` for this
def is a truncated parse artifact (`{"const":"f"}`); the HOL source above is
the authority and is what is ported here. -/
def compose6 (f p1 p2 p3 p4 p5 p6 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  f (p1 x1 x2 x3 x4 x5 x6) (p2 x1 x2 x3 x4 x5 x6) (p3 x1 x2 x3 x4 x5 x6)
    (p4 x1 x2 x3 x4 x5 x6) (p5 x1 x2 x3 x4 x5 x6) (p6 x1 x2 x3 x4 x5 x6)

/-- HOL `mk_126` (nonlin_def.hl:267-268). -/
def mk126 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f projX1 projX2 two6 two6 two6 projX6

/-- HOL `mk_456` (nonlin_def.hl:270-271). -/
def mk456 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f two6 two6 two6 projX4 projX5 projX6

/-- HOL `mk_135` (nonlin_def.hl:273-274). -/
def mk135 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 f projX1 two6 projX3 two6 projX5 two6

/-- Pins the whole `compose6`/`proj`/`two6` stack for `mk_126`:
setting the 3/4/5 slots to the constant 2. -/
example : mk126 f x1 x2 x3 x4 x5 x6 = f x1 x2 2 2 2 x6 := rfl

example : mk135 f x1 x2 x3 x4 x5 x6 = f x1 2 x3 2 x5 2 := rfl

example : mk456 f x1 x2 x3 x4 x5 x6 = f 2 2 2 x4 x5 x6 := rfl

/-- HOL `promote1_to_6` (nonlin_def.hl:254-255). -/
def promote1To6 (f : ℝ → ℝ) (x1 _x2 _x3 _x4 _x5 _x6 : ℝ) : ℝ := f x1

/-- HOL `promote3_to_6` (nonlin_def.hl:251-252). -/
def promote3To6 (f : ℝ → ℝ → ℝ → ℝ) (x1 x2 x3 _x4 _x5 _x6 : ℝ) : ℝ := f x1 x2 x3

example : promote1To6 f x1 x2 x3 x4 x5 x6 = f x1 := rfl

/-- Numeric: promotes a unary function onto the first slot. -/
example : promote1To6 Real.sqrt 9 0 0 0 0 0 = 3 := by
  unfold promote1To6
  rw [show (9 : ℝ) = 3 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]

example : promote3To6 (fun a b c => a + b + c) 1 2 3 4 5 6 = 6 := by
  norm_num [promote3To6]

/-- HOL `scalar6` (nonlin_def.hl:279-280). -/
def scalar6 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ) (r : ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x1 x2 x3 x4 x5 x6 * r

example : scalar6 f r x1 x2 x3 x4 x5 x6 = f x1 x2 x3 x4 x5 x6 * r := rfl

/-- Numeric: `scalar6 two6 3` is the constant 6. -/
example : scalar6 two6 3 1 1 1 1 1 1 = 6 := by norm_num [scalar6, two6, constant6]

/-- HOL `norm2hh` (sphere.hl:597-599). -/
noncomputable def norm2hh (y1 y2 y3 y4 y5 y6 : ℝ) : ℝ :=
  (y1 - hminus - hplus) ^ 2 + (y2 - 2) ^ 2 + (y3 - 2) ^ 2 + (y4 - 2) ^ 2 +
    (y5 - 2) ^ 2 + (y6 - 2) ^ 2

/-- Numeric: vanishes at the center `(hminus + hplus, 2,…,2)` — pins the
left-associated `y1 - hminus - hplus` grouping and the five `(yi - 2)²`. -/
example : norm2hh (hminus + hplus) 2 2 2 2 2 = 0 := by unfold norm2hh; ring

/-- Numeric: one unit off center in `y1` gives 1. -/
example : norm2hh (hminus + hplus + 1) 2 2 2 2 2 = 1 := by
  unfold norm2hh; ring

/-! ## Batch 3: the gamma/beta family (nonlin_def.hl + sphere.hl)

Reused, not re-ported: `dihXf`/`solY`/`upsX`/`deltaX` (SphereKit), `lfun`,
`mm1`, `mm2`, `bump` (PackingAuto2).  PackingAuto20/21 already carry verbatim
twins of `vol_x` (`volXf`) and `gamma2_x_div_azim_v2`, but those modules each
declare their own unsuffixed `atn2`/`dihXf`/`dihY`/`solY` — the fatal clash
SphereKit.lean:10-11 exists to remove — so they cannot be imported alongside
SphereKit.  The canonical `volX`/`solX`/`gamma2XDivAzimV2` are therefore
(re)stated here; `solX` also replaces the `sorry` stub `solXP38`
(LocalAuto38.lean:75).

Function arithmetic below is pointwise (`Pi` instances on ℝ⁶ → ℝ), matching
HOL Light's overloaded `+`/`-`/`*` on 6-ary real functions. -/

/-- HOL `uni` (nonlin_def.hl:246-247): `uni (f,x) x1..x6 = f (x x1..x6)`; the
HOL pair argument is uncurried here. NB: defs.json's `body_ast` is a truncated
parse artifact (`{"const":"f"}`, the `(f:A->B)` type cast trips parse_defs);
the HOL source is the authority. -/
def uni (f : ℝ → ℝ) (x : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f (x x1 x2 x3 x4 x5 x6)

/-- Pins the uncurrying against the intended use `uni lfun g = lfun ∘ g`. -/
example : uni lfun g x1 x2 x3 x4 x5 x6 = lfun (g x1 x2 x3 x4 x5 x6) := rfl

/-- HOL `dummy6` (nonlin_def.hl:263): `constant6 (&0)`. -/
def dummy6 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ := constant6 0

example : dummy6 1 2 3 4 5 6 = 0 := rfl

/-- HOL `sol_x` (sphere.hl:181-184): solid angle from squared lengths.
Verbatim body against SphereKit's `dihXf`; replaces the `sorry` stub
`solXP38` (LocalAuto38.lean:75). -/
noncomputable def solX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  dihXf x1 x2 x3 x4 x5 x6 + dihXf x2 x3 x1 x5 x6 x4 +
    dihXf x3 x1 x2 x6 x4 x5 - Real.pi

/-- Consistency with the existing `solY` (SphereKit.lean:105):
`sol_y y = sol_x` at squared lengths. -/
example : solY y1 y2 y3 y4 y5 y6 =
    solX (y1 * y1) (y2 * y2) (y3 * y3) (y4 * y4) (y5 * y5) (y6 * y6) := rfl

/-- HOL `vol_x` (sphere.hl:251-252). Verbatim = `volXf`
(PackingAuto20.lean:99). -/
noncomputable def volX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  Real.sqrt (deltaX x1 x2 x3 x4 x5 x6) / 12

/-- Numeric: regular tetrahedron, `volX (4,…,4) = √128/12 = 2√2/3`. -/
example : volX 4 4 4 4 4 4 = 2 * Real.sqrt 2 / 3 := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have hs : Real.sqrt (128 : ℝ) = 8 * Real.sqrt 2 := by
    rw [show (128 : ℝ) = 8 ^ 2 * 2 by norm_num, Real.sqrt_mul (by norm_num),
      Real.sqrt_sq (by norm_num)]
  unfold volX
  rw [h128, hs]
  field_simp
  ring

/-- HOL `gamma2_x_div_azim_v2` (nonlin_def.hl:341-343). Verbatim =
PackingAuto21.lean:164 (`gamma2_x_div_azim_v2`); re-stated under the canonical
camelCase name because PackingAuto21 cannot be imported next to SphereKit. -/
noncomputable def gamma2XDivAzimV2 (m x : ℝ) : ℝ :=
  (8 - x) * Real.sqrt x / 24 -
    (2 * (2 * mm1 / Real.pi) * (1 - Real.sqrt x / Real.sqrt 8) -
      (8 * mm2 / Real.pi) * m * lfun (Real.sqrt x / 2))

/-- HOL `gamma2_x1_div_a_v2` (nonlin_def.hl:346-347). -/
noncomputable def gamma2X1DivAV2 (m : ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  promote1To6 (gamma2XDivAzimV2 m)

/-- Pins the `promote1_to_6` glue. -/
example : gamma2X1DivAV2 m x1 x2 x3 x4 x5 x6 = gamma2XDivAzimV2 m x1 := rfl

/-- HOL `vol3f_456` (nonlin_def.hl:365-378). Original batch-5 list member,
ported with batch 3 as a `gamma3_x` dependency. NB: only the first `lfun`
term carries the `scalar6 … m4` factor (HOL source asymmetry, verified
against nonlin_def.hl:371-377). -/
noncomputable def vol3f456 (m4 : ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  scalar6 (mk456 (rotate5 solX) + mk456 (rotate6 solX) + mk456 (rotate4 solX))
      (2 * mm1 / Real.pi) -
    scalar6
      ((scalar6 (uni lfun (scalar6 projY4 0.5)) m4) * mk456 (rotate4 dihXf) +
        (uni lfun (scalar6 projY5 0.5)) * mk456 (rotate5 dihXf) +
        (uni lfun (scalar6 projY6 0.5)) * mk456 (rotate6 dihXf))
      (8 * mm2 / Real.pi)

/-- HOL `gamma3_x` (nonlin_def.hl:380-381). -/
noncomputable def gamma3X (m4 : ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  mk456 volX - vol3f456 m4

/-- Pins the `mk_456` face selection: slots 1-3 set to the constant 2. -/
example : gamma3X m4 x1 x2 x3 x4 x5 x6 =
    volX 2 2 2 x4 x5 x6 - vol3f456 m4 x1 x2 x3 x4 x5 x6 := rfl

/-- HOL `gamma3f_x_div_sqrtdelta` (nonlin_def.hl:349-363). -/
noncomputable def gamma3fXDivSqrtdelta (m4 m5 m6 : ℝ) :
    ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  constant6 (1 / 12) -
    (scalar6
        (mk456 (rotate5 solEulerXDivSqrtdelta) +
          mk456 (rotate6 solEulerXDivSqrtdelta) +
          mk456 (rotate4 solEulerXDivSqrtdelta))
        (2 * mm1 / Real.pi) -
      scalar6
        ((scalar6 (uni lfun (scalar6 projY4 0.5)) m4) *
            mk456 (rotate4 dihXDivSqrtdeltaPosbranch) +
          (scalar6 (uni lfun (scalar6 projY5 0.5)) m5) *
            mk456 (rotate5 dihXDivSqrtdeltaPosbranch) +
          (scalar6 (uni lfun (scalar6 projY6 0.5)) m6) *
            mk456 (rotate6 dihXDivSqrtdeltaPosbranch))
        (8 * mm2 / Real.pi))

/-- HOL `gamma23_full8_x` (nonlin_def.hl:383-388). -/
noncomputable def gamma23Full8X (m1 : ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 (gamma3X m1) dummy6 dummy6 dummy6 projX1 projX2 projX6 +
    compose6 (gamma3X m1) dummy6 dummy6 dummy6 projX1 projX3 projX5 +
    scalar6 (dihXf - (mk126 dihXf + mk135 dihXf)) 0.008

/-- HOL `gamma23_keep135_x` (nonlin_def.hl:390-393). -/
noncomputable def gamma23Keep135X (m1 : ℝ) : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 (gamma3X m1) dummy6 dummy6 dummy6 projX1 projX3 projX5 +
    scalar6 (dihXf - mk135 dihXf) 0.008

/-- Pins the whole `compose6`/`dummy6`/`scalar6` glue for `gamma23_keep135_x`:
the `gamma3_x` composite sees slots 1-3 zeroed, and the correction term is
`0.008 * (dih_x - dih_x∘(x1,2,x3,2,x5,2))`. -/
example : gamma23Keep135X m1 x1 x2 x3 x4 x5 x6 =
    gamma3X m1 0 0 0 x1 x3 x5 +
      (dihXf x1 x2 x3 x4 x5 x6 - dihXf x1 2 x3 2 x5 2) * 0.008 := rfl

/-- Same pinning for `gamma23_full8_x`: two `gamma3_x` composites (keeping
126 resp. 135) plus `0.008 * (dih_x - dih_x∘(x1,x2,2,2,2,x6) -
dih_x∘(x1,2,x3,2,x5,2))`. -/
example : gamma23Full8X m1 x1 x2 x3 x4 x5 x6 =
    gamma3X m1 0 0 0 x1 x2 x6 + gamma3X m1 0 0 0 x1 x3 x5 +
      (dihXf x1 x2 x3 x4 x5 x6 -
        (dihXf x1 x2 2 2 2 x6 + dihXf x1 2 x3 2 x5 2)) * 0.008 := rfl

/-- HOL `beta_bump_force_y` (sphere.hl:614-615). -/
noncomputable def betaBumpForceY (y1 _y2 _y3 y4 _y5 _y6 : ℝ) : ℝ :=
  bump (y1 / 2) - bump (y4 / 2)

/-- Numeric: equal `y1 = y4` kills the force term. -/
example (y : ℝ) : betaBumpForceY y 0 0 y 0 0 = 0 := by
  unfold betaBumpForceY; ring

/-- HOL `beta_bump_lb` (sphere.hl:636). -/
def betaBumpLb : ℝ := -0.005

/-- Numeric/cross-def: `bump h0 = 0.005 = -beta_bump_lb` (bump peak value;
pins both the `bump` reuse and the sign of `betaBumpLb`). -/
example : bump h0 = -betaBumpLb := by norm_num [bump, h0, betaBumpLb]

/-! ## Batch 5: misc (sphere.hl / nonlin_def.hl / ineq.hl)

`matan` was already ported in batch 1 and is skipped.  `dart_std3_big`
(fallback-extracted at ineq.hl:3079) is verbatim `dart_std3`; `dart_std3`
itself was triaged "unsupported: set/list notation" by parse_defs, but the
`define_dart` list of (lo, value, hi) triples renders directly as a Lean
`List (ℝ × ℝ × ℝ)`. -/

/-- HOL `tame_table_d` (sphere.hl:803-805): the preferred term over
`d2_tame`. ℕ-valued table indices; `&r`/`&s` in the branches are ℕ→ℝ casts
(defs.json `num2r` nodes), the guard `r + 2*s > 3` is at ℕ level. -/
def tameTableD (r s : ℕ) : ℝ :=
  if r + 2 * s > 3 then
    0.103 * (2 - (s : ℝ)) + 0.2759 * ((r : ℝ) + 2 * (s : ℝ) - 4)
  else 0

/-- Numeric: `r + 2s = 3` takes the zero branch. -/
example : tameTableD 3 0 = 0 := by norm_num [tameTableD]

/-- Numeric: `tameTableD 5 1 = 0.103 + 0.2759 * 3 = 0.9307`. -/
example : tameTableD 5 1 = 0.9307 := by norm_num [tameTableD]

/-- HOL `dih2_y` (sphere.hl:163-165). -/
noncomputable def dih2Y (y1 y2 y3 y4 y5 y6 : ℝ) : ℝ :=
  dihY y2 y1 y3 y5 y4 y6

/-- HOL `dih3_y` (sphere.hl:166-168). -/
noncomputable def dih3Y (y1 y2 y3 y4 y5 y6 : ℝ) : ℝ :=
  dihY y3 y1 y2 y6 y4 y5

/-- Pins the `dih2_y` argument swap. -/
example : dih2Y y1 y2 y3 y4 y5 y6 = dihY y2 y1 y3 y5 y4 y6 := rfl

/-- Pins the `dih3_y` argument rotation. -/
example : dih3Y y1 y2 y3 y4 y5 y6 = dihY y3 y1 y2 y6 y4 y5 := rfl

/-- HOL `lfun_y1` (sphere.hl:789-790): the 6-ary `lfun y1`. -/
noncomputable def lfunY1 (y1 _y2 _y3 _y4 _y5 _y6 : ℝ) : ℝ := lfun y1

/-- `lfun_y1` is exactly `promote1_to_6 lfun`. -/
example : lfunY1 = promote1To6 lfun := rfl

/-- HOL `rho_x` (sphere.hl:137-140). -/
def rhoX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  -x1 * x1 * x4 * x4 - x2 * x2 * x5 * x5 - x3 * x3 * x6 * x6 +
    2 * x1 * x2 * x4 * x5 + 2 * x1 * x3 * x4 * x6 + 2 * x2 * x3 * x5 * x6

/-- Numeric: `rhoX (1,…,1) = -3 + 6 = 3`. -/
example : rhoX 1 1 1 1 1 1 = 3 := by norm_num [rhoX]

/-- HOL `ups_126` (nonlin_def.hl:446-447). -/
def ups126 : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ :=
  compose6 (promote3To6 upsX) projX1 projX2 projX6 dummy6 dummy6 dummy6

/-- Pins the full stack: `ups_126` keeps slots 1,2,6 and zeroes 3,4,5
(`dummy6`), i.e. it is `ups_x x1 x2 x6`. -/
example : ups126 x1 x2 x3 x4 x5 x6 = upsX x1 x2 x6 := rfl

/-- HOL `dart_std3` (ineq.hl:2697-2704, via `define_dart`): the standard dart
domain box as a literal list of (lo, value, hi) triples — the shape consumed
by HOL `ineq`. parse_defs triaged this "unsupported: set/list notation", but
the list is directly portable; every entry pins `2.0 ≤ yi ≤ 2.52`. -/
def dartStd3 (y1 y2 y3 y4 y5 y6 : ℝ) : List (ℝ × ℝ × ℝ) :=
  [(2.0, y1, 2.52), (2.0, y2, 2.52), (2.0, y3, 2.52),
    (2.0, y4, 2.52), (2.0, y5, 2.52), (2.0, y6, 2.52)]

/-- HOL `dart_std3_big` (ineq.hl:3079, fallback extraction): `dart_std3_big =
dart_std3` — "same domain but extra disjunct" (the extra disjunct lives on the
inequality side, not in the domain). -/
def dartStd3Big : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → List (ℝ × ℝ × ℝ) := dartStd3

example : dartStd3Big = dartStd3 := rfl

/-- Numeric/structural: six entries, all `[2.0, ·, 2.52]`. -/
example : dartStd3 2.2 2.2 2.2 2.2 2.2 2.2 = List.replicate 6 (2.0, 2.2, 2.52) :=
  rfl

/-! ## Batch 6: tail sweep (sphere.hl constants and small combos)

The two former C-tier rows are re-ported under canonical names: `eta_y`
(PackingAuto21.lean:177) and `rad2_x` (`rad2XP25`, PackingAuto25.lean:89) are
`sorry` stubs there, and PackingAuto21/25 cannot be co-imported with SphereKit
anyway (the `atn2` clash, SphereKit.lean:10-11). -/

/-- HOL `sqrt8` (sphere.hl:75). PackingAuto2 inlines this constant as
`Real.sqrt 8` (PackingAuto2.lean:91); named here for closure gluing. -/
noncomputable def sqrt8 : ℝ := Real.sqrt 8

/-- HOL `sqrt2` (sphere.hl:76). Same inlining note as `sqrt8`. -/
noncomputable def sqrt2 : ℝ := Real.sqrt 2

/-- Cross-def: `sqrt8 = 2 * sqrt2`. -/
example : sqrt8 = 2 * sqrt2 := by
  rw [sqrt8, sqrt2, show (8 : ℝ) = 2 ^ 2 * 2 by norm_num,
    Real.sqrt_mul (by norm_num), Real.sqrt_sq (by norm_num)]

example : sqrt2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)

/-- HOL `a_spine5` (sphere.hl:632). -/
def aSpine5 : ℝ := 0.0560305

/-- HOL `b_spine5` (sphere.hl:634). -/
def bSpine5 : ℝ := -0.0445813

example : (aSpine5, bSpine5) = (0.0560305, -0.0445813) := rfl

/-- HOL `eta_x` (sphere.hl:127-129). -/
noncomputable def etaX (x1 x2 x3 : ℝ) : ℝ :=
  Real.sqrt (x1 * x2 * x3 / upsX x1 x2 x3)

/-- Numeric: edge-2 regular simplex, `etaX 4 4 4 = √(64/48) = 2/√3`. -/
example : etaX 4 4 4 = 2 / Real.sqrt 3 := by
  have hups : upsX 4 4 4 = 48 := by norm_num [upsX]
  unfold etaX
  rw [hups, show (4 : ℝ) * 4 * 4 / 48 = (2 / Real.sqrt 3) ^ 2 by
    rw [div_pow, Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3)]; norm_num,
    Real.sqrt_sq (by positivity)]

/-- HOL `eta_y` (sphere.hl:131-135): `eta_x` at squared lengths (the HOL
let-chain). Canonical name for the `sorry` opaque `eta_y`
(PackingAuto21.lean:177). -/
noncomputable def etaY (y1 y2 y3 : ℝ) : ℝ :=
  etaX (y1 * y1) (y2 * y2) (y3 * y3)

example : etaY 2 2 2 = etaX 4 4 4 := by norm_num [etaY]

/-- HOL `rad2_x` (sphere.hl:271-273): squared circumradius from squared edge
lengths. Canonical name for the `sorry` stub `rad2XP25`
(PackingAuto25.lean:89). -/
noncomputable def rad2X (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rhoX x1 x2 x3 x4 x5 x6 / (deltaX x1 x2 x3 x4 x5 x6 * 4)

/-- Numeric: regular tetrahedron with edge 2 has circumradius `√6/2`, so
`rad2X (4,…,4) = 3/2`. -/
example : rad2X 4 4 4 4 4 4 = 1.5 := by norm_num [rad2X, rhoX, deltaX]

/-- HOL `x1_delta_x` (sphere.hl:840). -/
def x1DeltaX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := x1 * deltaX x1 x2 x3 x4 x5 x6

example : x1DeltaX 4 4 4 4 4 4 = 512 := by norm_num [x1DeltaX, deltaX]

/-! ## Axiom audit (standard three only: propext / Classical.choice /
Quot.sound) -/

#print axioms dihXDivSqrtdeltaPosbranch
#print axioms ldih6XDivSqrtdeltaPosbranch
#print axioms solEulerXDivSqrtdelta
#print axioms solEuler156XDivSqrtdelta
#print axioms delta4SquaredX
#print axioms matan
#print axioms compose6
#print axioms mk126
#print axioms norm2hh
#print axioms gamma3fXDivSqrtdelta
#print axioms gamma23Full8X
#print axioms vol3f456
#print axioms betaBumpForceY
#print axioms tameTableD
#print axioms ups126
#print axioms dartStd3Big
#print axioms etaY
#print axioms rad2X
#print axioms x1DeltaX

end Kepler.Text
