/-
Kepler.Text.IneqClosureDefs — P6-E batch 1: the `sqrtdelta` rational family of
the 155-definition closure of the 993 Flyspeck nonlinear inequalities
(work order: `docs/ineq-closure-155.md`, generated by
`lean/scripts/closure155.py`).

Convention B ports: camelCase renames, each def carries its HOL anchor
(`/-- HOL \`name\` (file:line) -/`).  Dependencies already in Lean are reused,
not re-ported: `deltaX`/`deltaX4` (SphereKit), `lfun`/`h0` (PackingAuto2:461,
same body as sphere.hl:525).  Batch-1 enablers ported here because nothing
else provided them: `matan` and the argument permuters `rotate2`–`rotate6`.

Every def is followed by a correctness valve: `rfl` identity checks that pin
the argument permutations / definitional glue, plus closed-form numeric
spot-checks at the regular-tetrahedron point `x = (4,…,4)` (squared edge
lengths of the tetrahedron with all edges 2), where
`deltaX = 128`, `deltaX4 = 16`, `sqrt 16 = 4`, `sqrt 8 = 2√2` make the HOL
bodies evaluate in closed form.  The same sample values were recomputed from
the kepler-g4e `defs.json` ASTs (see docs/ineq-closure-155.md header).
-/

import Kepler.Text.SphereKit
import Kepler.Text.PackingAuto2

namespace Kepler.Text

/-! ## Enablers: `matan` and the `rotate2`–`rotate6` permuters (sphere.hl) -/

/-- HOL `matan` (sphere.hl:728-731): the modified arctangent, analytic
continuation of `ArcTan[Sqrt[x]]/Sqrt[x]`. -/
noncomputable def matan (x : ℝ) : ℝ :=
  if x = 0 then 1
  else if x > 0 then Real.arctan (Real.sqrt x) / Real.sqrt x
  else Real.log ((1 + Real.sqrt (-x)) / (1 - Real.sqrt (-x))) /
    (2 * Real.sqrt (-x))

/-- `matan` at the removable singularity. -/
example : matan 0 = 1 := by unfold matan; rw [if_pos rfl]

/-- Positive branch, `x = 1`: `atn(1)/1 = π/4`. -/
example : matan 1 = Real.pi / 4 := by
  unfold matan
  rw [if_neg (by norm_num), if_pos (by norm_num), Real.sqrt_one,
    Real.arctan_one, div_one]

/-- Negative branch, `x = -1`: `(1+1)/(1-1) = 2/0 = 0`, so `log 0 = 0` and the
whole quotient is `0` (junk-value semantics; pins the `--x` translation). -/
example : matan (-1) = 0 := by
  unfold matan
  rw [if_neg (by norm_num), if_neg (by norm_num)]
  norm_num [Real.log_zero]

/-- The positive branch really is `arctan(√x)/√x` (catches a flipped
numerator/denominator). -/
example {x : ℝ} (hx : 0 < x) :
    matan x * Real.sqrt x = Real.arctan (Real.sqrt x) := by
  unfold matan
  rw [if_neg (ne_of_gt hx), if_pos hx]
  exact div_mul_cancel₀ _ (Real.sqrt_ne_zero'.mpr hx)

/-- HOL `rotate2` (sphere.hl:654-655). -/
def rotate2 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x2 x3 x1 x5 x6 x4

/-- HOL `rotate3` (sphere.hl:657-658). -/
def rotate3 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x3 x1 x2 x6 x4 x5

/-- HOL `rotate4` (sphere.hl:660-661). -/
def rotate4 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x4 x2 x6 x1 x5 x3

/-- HOL `rotate5` (sphere.hl:663-664). -/
def rotate5 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x5 x3 x4 x2 x6 x1

/-- HOL `rotate6` (sphere.hl:666-667). -/
def rotate6 (f : ℝ → ℝ → ℝ → ℝ → ℝ → ℝ → ℝ)
    (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ := f x6 x1 x5 x3 x4 x2

/-- `rotate2`/`rotate3` are inverse 3-cycles on the argument triples
`(x1 x2 x3)` and `(x4 x5 x6)` — pins both permutation tables at once. -/
example : rotate2 (rotate3 f) x1 x2 x3 x4 x5 x6 = f x1 x2 x3 x4 x5 x6 := rfl

/-- Two `rotate2`s make one `rotate3`. -/
example : rotate2 (rotate2 f) x1 x2 x3 x4 x5 x6 = rotate3 f x1 x2 x3 x4 x5 x6 :=
  rfl

/-! ## Batch 1: the `sqrtdelta` rational family (nonlin_def.hl) -/

/-- HOL `dih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:138-142): a valid
formula for `dih_x / sqrt(delta_x)` when `delta_x > 0` and
`delta_x4 ≠ 0`; "posbranch" = no `pi_shift` term (the `d_x4 ≥ 0` branch of
`dih_x_div_sqrtdelta`, nonlin_def.hl:132). -/
noncomputable def dihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let dX4 := deltaX4 x1 x2 x3 x4 x5 x6
  let d := deltaX x1 x2 x3 x4 x5 x6
  (Real.sqrt (4 * x1) / dX4) * matan (4 * x1 * d / dX4 ^ 2)

/-- Regular-tetrahedron spot-check: at `x = (4,…,4)`,
`deltaX = 128`, `deltaX4 = 16`, so the body is
`sqrt(16)/16 * matan(16*128/256) = matan(8)/4 = arctan(2√2)/(8√2)`
(the HOL-side value, since `matan 8 = atn(√8)/√8`). -/
example : dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    Real.arctan (2 * Real.sqrt 2) / (8 * Real.sqrt 2) := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have h16 : deltaX4 4 4 4 4 4 4 = 16 := by norm_num [deltaX4]
  have hs16 : Real.sqrt (16 : ℝ) = 4 := by
    rw [show (16 : ℝ) = 4 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs8 : Real.sqrt (8 : ℝ) = 2 * Real.sqrt 2 := by
    rw [show (8 : ℝ) = 2 ^ 2 * 2 by norm_num, Real.sqrt_mul (by norm_num),
      Real.sqrt_sq (by norm_num)]
  have hs2 : Real.sqrt (2 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  unfold dihXDivSqrtdeltaPosbranch
  rw [h128, h16]
  show Real.sqrt (4 * 4) / 16 * matan (4 * 4 * 128 / 16 ^ 2) = _
  unfold matan
  rw [show (4 : ℝ) * 4 * 128 / 16 ^ 2 = 8 by norm_num,
    if_neg (show ¬(8 : ℝ) = 0 by norm_num),
    if_pos (show (0 : ℝ) < 8 by norm_num),
    show (4 : ℝ) * 4 = 16 by norm_num, hs16, hs8]
  field_simp
  ring

/-- HOL `dih4_x_div_sqrtdelta_posbranch` (nonlin_def.hl:163-164):
`rotate4 dih_x_div_sqrtdelta_posbranch` (η-expanded). -/
noncomputable def dih4XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate4` argument order for this instance. -/
example : dih4XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    dihXDivSqrtdeltaPosbranch x4 x2 x6 x1 x5 x3 := rfl

/-- HOL `ldih_x_div_sqrtdelta_posbranch` (nonlin_def.hl:144-146); the HOL
`lfun` (sphere.hl:525) is `Kepler.Text.lfun` (PackingAuto2.lean:461). -/
noncomputable def ldihXDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  lfun (Real.sqrt x1 / 2) * dihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Spot-check: at `x = (4,…,4)`, `lfun (sqrt 4 / 2) = lfun 1 = 1`, so `ldih`
collapses to `dih`. -/
example : ldihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 =
    dihXDivSqrtdeltaPosbranch 4 4 4 4 4 4 := by
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold ldihXDivSqrtdeltaPosbranch
  rw [hs4]
  norm_num [lfun, h0]

/-- HOL `ldih2_x_div_sqrtdelta_posbranch` (nonlin_def.hl:148-149). -/
noncomputable def ldih2XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate2 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih3_x_div_sqrtdelta_posbranch` (nonlin_def.hl:151-152). -/
noncomputable def ldih3XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate3 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih5_x_div_sqrtdelta_posbranch` (nonlin_def.hl:154-155). -/
noncomputable def ldih5XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- HOL `ldih6_x_div_sqrtdelta_posbranch` (nonlin_def.hl:157-158). -/
noncomputable def ldih6XDivSqrtdeltaPosbranch (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 ldihXDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6

/-- Pins the `rotate2` instance (others follow from the generic `rotate`
checks above). -/
example : ldih2XDivSqrtdeltaPosbranch x1 x2 x3 x4 x5 x6 =
    ldihXDivSqrtdeltaPosbranch x2 x3 x1 x5 x6 x4 := rfl

/-- HOL `sol_euler_x_div_sqrtdelta` (nonlin_def.hl:115-119). Valid when the
let-bound `a > 0`; `a` is verbatim the body of `eulerA_x`
(sphere.hl:830-833). -/
noncomputable def solEulerXDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  let a := Real.sqrt (x1 * x2 * x3) + Real.sqrt x1 * (x2 + x3 - x4) / 2 +
    Real.sqrt x2 * (x1 + x3 - x5) / 2 + Real.sqrt x3 * (x1 + x2 - x6) / 2
  matan (deltaX x1 x2 x3 x4 x5 x6 / (4 * a ^ 2)) / a

/-- Regular-tetrahedron spot-check: `a = 8 + 4 + 4 + 4 = 20`,
`deltaX = 128`, so the value is `matan(128/1600)/20 = matan(2/25)/20`. -/
example : solEulerXDivSqrtdelta 4 4 4 4 4 4 = matan (2 / 25) / 20 := by
  have h128 : deltaX 4 4 4 4 4 4 = 128 := by norm_num [deltaX]
  have hs64 : Real.sqrt ((4 : ℝ) * 4 * 4) = 8 := by
    rw [show (4 : ℝ) * 4 * 4 = 8 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  have hs4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  unfold solEulerXDivSqrtdelta
  norm_num [h128, hs64, hs4]

/-- HOL `sol_euler246_x_div_sqrtdelta` (nonlin_def.hl:121-122):
`rotate4 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler246XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate4 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler345_x_div_sqrtdelta` (nonlin_def.hl:124-125):
`rotate5 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler345XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate5 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- HOL `sol_euler156_x_div_sqrtdelta` (nonlin_def.hl:127-128):
`rotate6 sol_euler_x_div_sqrtdelta` (η-expanded). -/
noncomputable def solEuler156XDivSqrtdelta (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  rotate6 solEulerXDivSqrtdelta x1 x2 x3 x4 x5 x6

/-- Pins the `rotate6` instance against the base definition. -/
example : solEuler156XDivSqrtdelta x1 x2 x3 x4 x5 x6 =
    solEulerXDivSqrtdelta x6 x1 x5 x3 x4 x2 := rfl

/-- HOL `delta4_squared_x` (sphere.hl:835-836). -/
noncomputable def delta4SquaredX (x1 x2 x3 x4 x5 x6 : ℝ) : ℝ :=
  deltaX4 x1 x2 x3 x4 x5 x6 ^ 2

/-- Numeric spot-check: `deltaX4 (4,…,4) = 16`, squared is 256 (pins `pow 2`
as a real square). -/
example : delta4SquaredX 4 4 4 4 4 4 = 256 := by
  norm_num [delta4SquaredX, deltaX4]

/-! ## Axiom audit (standard three only: propext / Classical.choice /
Quot.sound) -/

#print axioms dihXDivSqrtdeltaPosbranch
#print axioms ldih6XDivSqrtdeltaPosbranch
#print axioms solEulerXDivSqrtdelta
#print axioms solEuler156XDivSqrtdelta
#print axioms delta4SquaredX
#print axioms matan

end Kepler.Text
