/-
  Phase 4, G4 certificate (auto-generated by pipeline/interval/emit_lean.py).
  case: FWGKMBZ  (orig_op: >, vars: ['hminus', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6'])
  cert: 205418 leaf/leaves, prec 64 (bb_arb)
  Do not edit by hand.
-/
import Kepler.Interval.CertBool

namespace Kepler.Interval.Cases

/-- The case expression (RPN prog mirrored as `IExpr`). -/
def CFWGKMBZExpr : IExpr 7 :=
  (.sub (.sub (.sub (.sub (.sub (.add (.add (.mul (.mul (.mul (.var 1) (.var 1)) (.mul (.var 4) (.var 4))) (.add (.add (.sub (.add (.add (.neg (.mul (.var 1) (.var 1))) (.mul (.var 2) (.var 2))) (.mul (.var 3) (.var 3))) (.mul (.var 4) (.var 4))) (.mul (.var 5) (.var 5))) (.mul (.var 6) (.var 6)))) (.mul (.mul (.mul (.var 2) (.var 2)) (.mul (.var 5) (.var 5))) (.add (.sub (.add (.add (.sub (.mul (.var 1) (.var 1)) (.mul (.var 2) (.var 2))) (.mul (.var 3) (.var 3))) (.mul (.var 4) (.var 4))) (.mul (.var 5) (.var 5))) (.mul (.var 6) (.var 6))))) (.mul (.mul (.mul (.var 3) (.var 3)) (.mul (.var 6) (.var 6))) (.sub (.add (.add (.sub (.add (.mul (.var 1) (.var 1)) (.mul (.var 2) (.var 2))) (.mul (.var 3) (.var 3))) (.mul (.var 4) (.var 4))) (.mul (.var 5) (.var 5))) (.mul (.var 6) (.var 6))))) (.mul (.mul (.mul (.var 2) (.var 2)) (.mul (.var 3) (.var 3))) (.mul (.var 4) (.var 4)))) (.mul (.mul (.mul (.var 1) (.var 1)) (.mul (.var 3) (.var 3))) (.mul (.var 5) (.var 5)))) (.mul (.mul (.mul (.var 1) (.var 1)) (.mul (.var 2) (.var 2))) (.mul (.var 6) (.var 6)))) (.mul (.mul (.mul (.var 4) (.var 4)) (.mul (.var 5) (.var 5))) (.mul (.var 6) (.var 6)))) (.const ⟨0, 0⟩))

/-- The target box (dyadic q-expansion of the original decimal box). -/
def CFWGKMBZBox : Fin 7 → DInterval :=
  ![⟨⟨322122547, -28⟩, ⟨348966093, -28⟩⟩, ⟨⟨2576980377, -30⟩, ⟨711568707, -28⟩⟩, ⟨⟨2, 0⟩, ⟨759250125, -28⟩⟩, ⟨⟨2, 0⟩, ⟨759250125, -28⟩⟩, ⟨⟨2, 0⟩, ⟨759250125, -28⟩⟩, ⟨⟨2, 0⟩, ⟨759250125, -28⟩⟩, ⟨⟨2, 0⟩, ⟨759250125, -28⟩⟩]

end Kepler.Interval.Cases
